// Generated by cc for application "petstore". Do not edit: recompiling overwrites
// this file. To change what is generated, edit cc.yaml in your source tree.
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

export const petApiApi = new aws.apigatewayv2.Api("pet-api", {
    name: "petstore-pet-api",
    protocolType: "HTTP",
});

export const mainLogs = new aws.cloudwatch.LogGroup("main", {
    name: "/aws/lambda/petstore-main",
    retentionInDays: 14,
});

export const petsByOwnerTable = new aws.dynamodb.Table("petsByOwner", {
    attributes: [
        {
            name: "id",
            type: "S",
        },
    ],
    billingMode: "PAY_PER_REQUEST",
    hashKey: "id",
    name: "petstore-petsByOwner",
});

export const mainRole = new aws.iam.Role("main", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "petstore-main-role",
});

export const mainPolicy = new aws.iam.RolePolicy("main", {
    name: "petstore-main-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                petsByOwnerTable.arn,
                pulumi.interpolate`${petsByOwnerTable.arn}/index/*`,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: mainRole.id,
});

const mainEnv: { [key: string]: pulumi.Input<string> } = {
    CC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CC_AWS_ENDPOINT_URL ?? ""}`,
    CC_KV_PETSBYOWNER_TABLE: pulumi.interpolate`${petsByOwnerTable.name}`,
};

export const mainFn = new aws.lambda.Function("main", {
    code: new pulumi.asset.FileArchive("build/main.zip"),
    environment: { variables: mainEnv },
    handler: "cc_lambda_entry.handler",
    memorySize: 512,
    name: "petstore-main",
    role: mainRole.arn,
    runtime: "python3.12",
    timeout: 30,
});

export const petApiIntegration = new aws.apigatewayv2.Integration("pet-api", {
    apiId: petApiApi.id,
    integrationMethod: "POST",
    integrationType: "AWS_PROXY",
    integrationUri: mainFn.arn,
    payloadFormatVersion: "2.0",
});

export const petApiRoute = new aws.apigatewayv2.Route("pet-api", {
    apiId: petApiApi.id,
    routeKey: "$default",
    target: pulumi.interpolate`integrations/${petApiIntegration.id}`,
});

export const petApiStage = new aws.apigatewayv2.Stage("pet-api", {
    apiId: petApiApi.id,
    autoDeploy: true,
    name: "$default",
});

export const petApiPermission = new aws.lambda.Permission("pet-api", {
    action: "lambda:InvokeFunction",
    function: mainFn.name,
    principal: "apigateway.amazonaws.com",
    sourceArn: pulumi.interpolate`${petApiApi.executionArn}/*/*`,
});

// Stack outputs. Every environment binding is exported under the exact
// name the runtime shims read, so a compiled unit can be run locally with:
//   eval "$(pulumi output --json | jq -r 'to_entries[]|"export \(.key)=\(.value)"')"
export const CC_GATEWAY_PET_API_URL = pulumi.interpolate`${petApiApi.apiEndpoint}`;
export const CC_KV_PETSBYOWNER_TABLE = pulumi.interpolate`${petsByOwnerTable.name}`;
export const petApiUrl = petApiApi.apiEndpoint;
