// Generated by cloudcc. Lambda entrypoint for execution unit "main".
//
// Do not edit: recompiling overwrites this file.

import * as _cloudccPubsub from "./_cloudcc_runtime/pubsub.js";
import serverless from "serverless-http";

const _module = await import("./server.js");
const _http = serverless(_module.app);

/**
 * Route the invocation to the right adapter.
 *
 * A single unit can be both an HTTP handler and a topic subscriber, so the
 * event shape decides: SNS deliveries go to the registered subscribers, and
 * anything else is treated as an HTTP request.
 */
export async function handler(event, context) {
  if (_cloudccPubsub.isSnsEvent(event)) {
    return _cloudccPubsub.dispatch(event);
  }
  return _http(event, context);
}
