"""Architecture of petstore-node, generated by cloudcc.

Diagram as code, using https://pypi.org/project/diagrams -- one icon per
capability, showing the service each one resolved to and how the program said
they are connected.

The supporting cast is deliberately absent: roles, policies, log groups and an
HTTP API's internal wiring all exist, and all of them are in architecture.mmd
and architecture.dot. This file answers "what is this system", not "what will
exist in the account".

    pip install diagrams   # and graphviz
    python architecture.py

Recompiling overwrites this file. Copy it before editing.
"""

from diagrams import Diagram, Edge
from diagrams.aws.compute import Lambda
from diagrams.aws.database import Dynamodb
from diagrams.aws.network import APIGateway

with Diagram(
    "petstore-node",
    filename="petstore-node-architecture",
    outformat="png",
    show=False,
    direction="LR",
):
    n_execution_unit_main = Lambda("main\nLambda")
    n_expose_pet_api = APIGateway("pet-api\nAPI Gateway")
    n_persist_kv_petsByOwner = Dynamodb("petsByOwner\nDynamoDB")

    n_expose_pet_api >> n_execution_unit_main
    n_execution_unit_main >> n_persist_kv_petsByOwner
