"""Architecture of petstore-node, generated by cloudcc.

Diagram as code, using https://pypi.org/project/diagrams -- rendered from the
same edges the compiler resolved, so it cannot show a resource that was not
compiled or omit one that was.

    pip install diagrams   # and graphviz
    python architecture.py

Recompiling overwrites this file. Copy it before editing.
"""

from diagrams import Cluster, Diagram, Edge
from diagrams.aws.compute import Lambda
from diagrams.aws.database import Dynamodb
from diagrams.aws.management import CloudwatchLogs
from diagrams.aws.network import APIGateway, APIGatewayEndpoint
from diagrams.aws.security import IAMPermissions, IAMRole

with Diagram(
    "petstore-node",
    filename="petstore-node-architecture",
    outformat="png",
    show=False,
    direction="LR",
):
    with Cluster("main"):
        n_aws_cloudwatch_loggroup_main = CloudwatchLogs("main\ncloudwatch.loggroup")
        n_aws_iam_policy_main = IAMPermissions("main\niam.policy")
        n_aws_iam_role_main = IAMRole("main\niam.role")
        n_aws_lambda_main = Lambda("main\nlambda")
    n_aws_apigatewayv2_integration_pet_api = APIGatewayEndpoint("pet-api\napigatewayv2.integration")
    n_aws_apigatewayv2_route_pet_api = APIGatewayEndpoint("pet-api\napigatewayv2.route")
    n_aws_apigatewayv2_stage_pet_api = APIGatewayEndpoint("pet-api\napigatewayv2.stage")
    n_aws_apigatewayv2_pet_api = APIGateway("pet-api\napigatewayv2")
    n_aws_dynamodb_petsByOwner = Dynamodb("petsByOwner\ndynamodb")
    n_aws_lambda_permission_pet_api = IAMPermissions("pet-api\nlambda.permission")

    n_aws_apigatewayv2_integration_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_pet_api
    n_aws_apigatewayv2_integration_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_lambda_main
    n_aws_apigatewayv2_route_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_integration_pet_api
    n_aws_apigatewayv2_route_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_pet_api
    n_aws_apigatewayv2_stage_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_route_pet_api
    n_aws_apigatewayv2_stage_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_pet_api
    n_aws_iam_policy_main >> Edge(color="gray60", style="dashed") >> n_aws_dynamodb_petsByOwner
    n_aws_iam_policy_main >> Edge(color="gray60", style="dashed") >> n_aws_iam_role_main
    n_aws_lambda_permission_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_pet_api
    n_aws_lambda_permission_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_lambda_main
    n_aws_lambda_main >> Edge(color="gray60", style="dashed") >> n_aws_cloudwatch_loggroup_main
    n_aws_lambda_main >> Edge(color="gray60", style="dashed") >> n_aws_iam_role_main
    n_aws_lambda_main >> Edge(label="uses") >> n_aws_dynamodb_petsByOwner
