// Generated by cloudcc for application "petstore-node". Do not edit: recompiling overwrites
// this file. To change what is generated, edit cloudcc.yaml in your source tree.
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const petApiApi = new aws.apigatewayv2.Api("pet-api", {
    name: "petstore-node-pet-api",
    protocolType: "HTTP",
});

const mainLogs = new aws.cloudwatch.LogGroup("main", {
    name: "/aws/lambda/petstore-node-main",
    retentionInDays: 14,
});

const summaryLogs = new aws.cloudwatch.LogGroup("summary", {
    name: "/aws/lambda/petstore-node-summary",
    retentionInDays: 14,
});

const petsByOwnerTable = new aws.dynamodb.Table("petsByOwner", {
    attributes: [
        {
            name: "id",
            type: "S",
        },
    ],
    billingMode: "PAY_PER_REQUEST",
    hashKey: "id",
    name: "petstore-node-petsByOwner",
});

const mainRole = new aws.iam.Role("main", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "petstore-node-main-role",
});

const summaryRole = new aws.iam.Role("summary", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "petstore-node-summary-role",
});

const summaryEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_UNIT: `summary`,
};

const summaryFn = new aws.lambda.Function("summary", {
    code: new pulumi.asset.FileArchive("build/summary.zip"),
    environment: { variables: summaryEnv },
    handler: "index.handler",
    memorySize: 512,
    name: "petstore-node-summary",
    role: summaryRole.arn,
    runtime: "nodejs22.x",
    timeout: 30,
});

const mainPolicy = new aws.iam.RolePolicy("main", {
    name: "petstore-node-main-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                petsByOwnerTable.arn,
                pulumi.interpolate`${petsByOwnerTable.arn}/index/*`,
            ],
        },
        {
            Action: [
                "lambda:InvokeFunction",
            ],
            Effect: "Allow",
            Resource: [
                summaryFn.arn,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: mainRole.id,
});

const mainEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_KV_PETSBYOWNER_TABLE: pulumi.interpolate`${petsByOwnerTable.name}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_UNIT: `main`,
    CLOUDCC_UNIT_SUMMARY_FUNCTION: pulumi.interpolate`${summaryFn.name}`,
};

const mainFn = new aws.lambda.Function("main", {
    code: new pulumi.asset.FileArchive("build/main.zip"),
    environment: { variables: mainEnv },
    handler: "index.handler",
    memorySize: 512,
    name: "petstore-node-main",
    role: mainRole.arn,
    runtime: "nodejs22.x",
    timeout: 30,
});

const petApiIntegration = new aws.apigatewayv2.Integration("pet-api", {
    apiId: petApiApi.id,
    integrationMethod: "POST",
    integrationType: "AWS_PROXY",
    integrationUri: mainFn.arn,
    payloadFormatVersion: "2.0",
});

const petApiRoute = new aws.apigatewayv2.Route("pet-api", {
    apiId: petApiApi.id,
    routeKey: "$default",
    target: pulumi.interpolate`integrations/${petApiIntegration.id}`,
});

const petApiStage = new aws.apigatewayv2.Stage("pet-api", {
    apiId: petApiApi.id,
    autoDeploy: true,
    name: "$default",
});

const petApiPermission = new aws.lambda.Permission("pet-api", {
    action: "lambda:InvokeFunction",
    function: mainFn.name,
    principal: "apigateway.amazonaws.com",
    sourceArn: pulumi.interpolate`${petApiApi.executionArn}/*/*`,
    statementId: "petstore-node-pet-api-invoke",
});

// Stack outputs. Every environment binding is exported under the exact
// name the runtime shims read, so a compiled unit can be run locally with:
//   eval "$(pulumi output --json | jq -r 'to_entries[]|"export \(.key)=\(.value)"')"
export const CLOUDCC_GATEWAY_PET_API_URL = pulumi.interpolate`${petApiApi.apiEndpoint}`;
export const CLOUDCC_KV_PETSBYOWNER_TABLE = pulumi.interpolate`${petsByOwnerTable.name}`;
export const CLOUDCC_UNIT_MAIN_FUNCTION = pulumi.interpolate`${mainFn.name}`;
export const CLOUDCC_UNIT_SUMMARY_FUNCTION = pulumi.interpolate`${summaryFn.name}`;
export const petApiUrl = petApiApi.apiEndpoint;
