"""Architecture of k8s-web-ts, generated by cloudcc.

Diagram as code, using https://pypi.org/project/diagrams -- one icon per
capability, showing the service each one resolved to and how the program said
they are connected.

The supporting cast is deliberately absent: roles, policies, log groups and an
HTTP API's internal wiring all exist, and all of them are in architecture.mmd
and architecture.dot. This file answers "what is this system", not "what will
exist in the account".

    pip install diagrams   # and graphviz
    python architecture.py

Recompiling overwrites this file. Copy it before editing.
"""

from diagrams import Diagram, Edge
from diagrams.k8s.compute import Deploy
from diagrams.k8s.network import SVC

with Diagram(
    "k8s-web-ts",
    filename="k8s-web-ts-architecture",
    outformat="png",
    show=False,
    direction="LR",
):
    n_execution_unit_web = Deploy("web\nDeployment")
    n_expose_web_front = SVC("web-front\nService")

    n_expose_web_front >> n_execution_unit_web
