package node

import (
	"reflect"
	"strings"
	"testing"

	"github.com/cloudcompiler/cloudcc/internal/source"
)

// program builds a source set from a map of path to content, parsing whatever
// the Node frontend claims and leaving the rest -- a tsconfig.json is not
// source, and is read as data.
func program(t *testing.T, files map[string]string) *source.Set {
	t.Helper()
	set := source.NewSet("/tmp")
	t.Cleanup(set.Close)
	for p, content := range files {
		f := &source.File{Path: p, Content: []byte(content)}
		if (Frontend{}).Owns(p) {
			if err := (Frontend{}).Parse(f); err != nil {
				t.Fatalf("parsing %s: %v", p, err)
			}
		}
		set.Add(f)
	}
	return set
}

// A path alias is how most TypeScript projects of any size import their own
// code. Before this, the specifier was not relative, so it was taken for an npm
// package: the module never entered the closure, never reached the bundle, and
// the first sign was esbuild failing to resolve it -- minutes later, from a
// different tool, naming the specifier but not the reason.
func TestPathAliasesResolveToLocalFiles(t *testing.T) {
	files := program(t, map[string]string{
		"tsconfig.json": `{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": { "@/*": ["src/*"] }
  }
}`,
		"src/server.ts": `import { pets } from "@/store";`,
		"src/store.ts":  `export const pets = 1;`,
	})

	got, unresolved := closure(files, "src/server.ts", nil)
	if len(unresolved) != 0 {
		t.Fatalf("unresolved = %+v", unresolved)
	}
	if want := []string{"src/server.ts", "src/store.ts"}; !reflect.DeepEqual(got, want) {
		t.Errorf("closure = %v, want %v", got, want)
	}
}

// The most specific pattern wins, which is what TypeScript does and what a
// project with both a general and a narrow alias relies on.
func TestTheMostSpecificAliasWins(t *testing.T) {
	files := program(t, map[string]string{
		"tsconfig.json": `{
  "compilerOptions": {
    "paths": {
      "@app/*": ["wrong/*"],
      "@app/models/*": ["right/*"]
    }
  }
}`,
		"server.ts":           `import { Pet } from "@app/models/pet";`,
		"right/pet.ts":        `export const Pet = 1;`,
		"wrong/models/pet.ts": `export const Pet = 2;`,
	})

	got, _ := closure(files, "server.ts", nil)
	if !contains(got, "right/pet.ts") || contains(got, "wrong/models/pet.ts") {
		t.Errorf("closure = %v, want the more specific pattern to win", got)
	}
}

// baseUrl alone, with no paths at all, is the other common shape.
func TestBaseURLResolvesBareSpecifiers(t *testing.T) {
	files := program(t, map[string]string{
		"tsconfig.json": `{ "compilerOptions": { "baseUrl": "src" } }`,
		"src/server.ts": `import { pets } from "store";`,
		"src/store.ts":  `export const pets = 1;`,
	})

	got, unresolved := closure(files, "src/server.ts", nil)
	if len(unresolved) != 0 {
		t.Fatalf("unresolved = %+v", unresolved)
	}
	if !contains(got, "src/store.ts") {
		t.Errorf("closure = %v, want src/store.ts", got)
	}
}

// The point of the whole exercise: an alias that maps to nothing is *reported*.
// Silence here is what the old behaviour did, and it is worse than the error,
// because the program looks compiled right up until the bundler runs.
func TestAnAliasThatMapsToNothingIsReported(t *testing.T) {
	files := program(t, map[string]string{
		"tsconfig.json": `{ "compilerOptions": { "paths": { "@/*": ["src/*"] } } }`,
		"server.ts":     `import { pets } from "@/store";`,
	})

	_, unresolved := closure(files, "server.ts", nil)
	if len(unresolved) != 1 {
		t.Fatalf("unresolved = %+v, want the alias reported", unresolved)
	}
	if unresolved[0].Rendered != "@/store" {
		t.Errorf("rendered = %q", unresolved[0].Rendered)
	}
	if !strings.Contains(unresolved[0].Why, "tsconfig") {
		t.Errorf("the reason should name where the mapping came from: %q", unresolved[0].Why)
	}
}

// An ordinary package import must stay silent. Every program has dozens, and
// warning about them would bury the case above.
func TestAPackageImportIsNotReported(t *testing.T) {
	files := program(t, map[string]string{
		"tsconfig.json": `{ "compilerOptions": { "paths": { "@/*": ["src/*"] } } }`,
		"server.ts":     `import express from "express";`,
	})

	_, unresolved := closure(files, "server.ts", nil)
	if len(unresolved) != 0 {
		t.Fatalf("unresolved = %+v, want npm packages left alone", unresolved)
	}
}

// A tsconfig is JSON with comments and trailing commas, which the standard
// decoder rejects. Every project generated by `tsc --init` has both.
func TestATsconfigMayHaveCommentsAndTrailingCommas(t *testing.T) {
	files := program(t, map[string]string{
		"tsconfig.json": `{
  // The project's own code is reached through "@/".
  "compilerOptions": {
    /* block comments too */
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"], // a trailing comment
    },
  },
}`,
		"src/server.ts": `import { pets } from "@/store";`,
		"src/store.ts":  `export const pets = 1;`,
	})

	got, unresolved := closure(files, "src/server.ts", nil)
	if len(unresolved) != 0 {
		t.Fatalf("unresolved = %+v", unresolved)
	}
	if !contains(got, "src/store.ts") {
		t.Errorf("closure = %v", got)
	}
}

// A `//` inside a string is not a comment. A URL in a paths entry is exactly
// where one shows up, and a regex-based stripper eats the rest of the line.
func TestStrippingCommentsLeavesStringsAlone(t *testing.T) {
	got := string(stripJSONC([]byte(`{"a": "https://example.com/x", "b": 1}`)))
	if want := `{"a": "https://example.com/x", "b": 1}`; got != want {
		t.Errorf("stripJSONC = %q, want %q", got, want)
	}
}

// One level of `extends` is read. Deeper than that is *said*, because a
// configuration read halfway resolves some aliases and not others, which is
// the one outcome worse than reading none.
func TestExtendsIsReadOnceAndDepthIsReported(t *testing.T) {
	files := program(t, map[string]string{
		"tsconfig.base.json": `{ "compilerOptions": { "baseUrl": ".", "paths": { "@/*": ["src/*"] } } }`,
		"tsconfig.json":      `{ "extends": "./tsconfig.base.json" }`,
		"src/server.ts":      `import { pets } from "@/store";`,
		"src/store.ts":       `export const pets = 1;`,
	})
	// `extends` names a file, not a directory: the base is read from the
	// directory it sits in.
	_, unresolved := closure(files, "src/server.ts", nil)
	for _, u := range unresolved {
		if strings.Contains(u.Why, "level deep") {
			t.Fatalf("one level should be read, not reported: %+v", u)
		}
	}
}

// A tsconfig this compiler cannot parse is reported once, not once per import.
func TestAnUnreadableTsconfigIsReportedOnce(t *testing.T) {
	files := program(t, map[string]string{
		"tsconfig.json": `{ this is not json`,
		"server.ts":     "import a from \"./a.js\";\nimport b from \"./b.js\";\n",
	})

	_, unresolved := closure(files, "server.ts", nil)
	config := 0
	for _, u := range unresolved {
		if strings.Contains(u.Why, "could not be read") {
			config++
		}
	}
	if config != 1 {
		t.Errorf("the unreadable tsconfig was reported %d times, want once: %+v", config, unresolved)
	}
}

// A type-only import reaches nothing at runtime: every TypeScript build erases
// the statement, and esbuild leaves the module out of the bundle. Following it
// into the closure puts that module in the unit anyway -- and when it declares
// a store, the unit is wired to one it never touches and granted IAM for it.
func TestATypeOnlyImportIsNotFollowed(t *testing.T) {
	files := program(t, map[string]string{
		"summary.ts": `import type { Pet } from "./store.js";
export async function describe(p: Pet): Promise<string> { return p.name; }`,
		"store.ts": `export interface Pet { name: string }
export const pets = 1;`,
	})

	got, _ := closure(files, "summary.ts", nil)
	if contains(got, "store.ts") {
		t.Errorf("closure = %v; a type-only import must not pull the module in", got)
	}
}

// The inline form is a different statement: the module is genuinely imported,
// and dropping it would leave a bundle missing a file the program calls into.
func TestAnInlineTypeImportIsStillAnImport(t *testing.T) {
	files := program(t, map[string]string{
		"server.ts": `import { type Pet, readPet } from "./store.js";
export const x = readPet;`,
		"store.ts": `export interface Pet { name: string }
export function readPet(): Pet { return { name: "x" }; }`,
	})

	got, _ := closure(files, "server.ts", nil)
	if !contains(got, "store.ts") {
		t.Errorf("closure = %v, want store.ts", got)
	}
}

// A tsconfig is user input, and a pattern whose prefix and suffix overlap the
// specifier crashed the resolver: "@a/b" starts with "@a/" and ends with "/b"
// while being shorter than both together, and the slice between them ran
// backwards.
func TestAnOverlappingAliasPatternDoesNotPanic(t *testing.T) {
	files := program(t, map[string]string{
		"tsconfig.json": `{ "compilerOptions": { "paths": { "@a/*/b": ["src/*"] } } }`,
		"server.ts":     `import x from "@a/b";`,
	})

	// The assertion is that this returns at all.
	if _, unresolved := closure(files, "server.ts", nil); len(unresolved) != 0 {
		t.Errorf("the specifier matches no pattern, so it is a package: %+v", unresolved)
	}
}
