package topology

import (
	"fmt"
	"sort"
	"strings"

	"github.com/cloudcompiler/cloudcc/internal/config"
	"github.com/cloudcompiler/cloudcc/internal/ir"
)

// PythonFile is the generated diagrams-as-code program.
//
// Mermaid and DOT describe the architecture in their own notations; this one
// describes it in Python, using mingrammer's `diagrams` package, and renders
// with the provider's own icons. It is worth having as a *file* rather than
// only as an image: it is the one output someone can edit -- move a cluster,
// drop the IAM noise, add an annotation for a review -- without hand-drawing
// anything, and it can be diffed in a pull request like the rest of the
// compiled tree.
const PythonFile = "architecture.py"

// diagramsNode maps a concrete resource kind to a class in the diagrams
// package.
//
// Every name here was read out of the installed package rather than guessed,
// because a wrong one is an ImportError at render time and the picture simply
// never appears. Anything unmapped falls back to a generic node, which is
// honest: an icon that is merely close is worse than an obviously plain box.
var diagramsNode = map[string]string{
	"aws.lambda": "aws.compute.Lambda",

	"aws.ecs.cluster":        "aws.compute.ECS",
	"aws.ecs.service":        "aws.compute.ElasticContainerServiceService",
	"aws.ecs.taskdefinition": "aws.compute.ElasticContainerServiceTask",
	"aws.ecr":                "aws.compute.ECR",

	"aws.iam.role":          "aws.security.IAMRole",
	"aws.iam.policy":        "aws.security.IAMPermissions",
	"aws.ecs.execrole":      "aws.security.IAMRole",
	"aws.ecs.taskrole":      "aws.security.IAMRole",
	"aws.ecs.taskpolicy":    "aws.security.IAMPermissions",
	"aws.lambda.permission": "aws.security.IAMPermissions",
	"aws.secretsmanager":    "aws.security.SecretsManager",

	"aws.cloudwatch.loggroup": "aws.management.CloudwatchLogs",

	"aws.apigatewayv2":             "aws.network.APIGateway",
	"aws.apigatewayv2.integration": "aws.network.APIGatewayEndpoint",
	"aws.apigatewayv2.route":       "aws.network.APIGatewayEndpoint",
	"aws.apigatewayv2.stage":       "aws.network.APIGatewayEndpoint",
	"aws.alb":                      "aws.network.ElbApplicationLoadBalancer",
	"aws.alb.targetgroup":          "aws.network.ELB",
	"aws.alb.listener":             "aws.network.ELB",
	"aws.vpc":                      "aws.network.VPC",
	"aws.vpc.subnet":               "aws.network.PrivateSubnet",
	"aws.vpc.securitygroup":        "aws.network.Nacl",
	"aws.vpc.gateway":              "aws.network.InternetGateway",
	"aws.vpc.routetable":           "aws.network.RouteTable",
	"aws.vpc.routeassoc":           "aws.network.RouteTable",

	"aws.dynamodb":    "aws.database.Dynamodb",
	"aws.rds":         "aws.database.RDS",
	"aws.elasticache": "aws.database.ElastiCache",
	"aws.memorydb":    "aws.database.ElasticacheForRedis",

	"aws.s3":         "aws.storage.S3",
	"aws.s3.object":  "aws.storage.SimpleStorageServiceS3Object",
	"aws.s3.website": "aws.storage.SimpleStorageServiceS3BucketWithObjects",

	"aws.sns":              "aws.integration.SNS",
	"aws.sns.subscription": "aws.integration.EventResource",
	"aws.sqs":              "aws.integration.SQS",
	"aws.kinesis":          "aws.analytics.KinesisDataStreams",
}

const fallbackNode = "aws.general.General"

// nodeClass returns the fully qualified diagrams class for a resource kind.
func nodeClass(kind string) string {
	if cls, ok := diagramsNode[kind]; ok {
		return cls
	}
	return fallbackNode
}

// nodeName is what the class is called once imported, which is what a call
// site must use: `from diagrams.aws.compute import Lambda` binds Lambda, not
// aws.compute.Lambda.
func nodeName(kind string) string {
	cls := nodeClass(kind)
	return cls[strings.LastIndex(cls, ".")+1:]
}

// Python renders the resolved architecture as a diagrams program.
//
// Only the resource layer gets one. The capability layer has no icons to draw
// with -- "a key/value store" is not an AWS service -- and a picture that
// invented icons for it would be claiming something the program never said.
func Python(p *ir.Program, opts Options) []byte {
	resources := nodes(p, Resources)

	// Group by the intent each resource expanded from, so an execution unit
	// and its role, log group and permissions read as one thing rather than as
	// four unrelated icons. The rest -- tables, buckets, topics -- stay at the
	// top level, because they are shared and boxing them would imply an
	// ownership that is not there.
	clustered := map[string][]ir.Key{}
	loose := []ir.Key{}
	for _, key := range resources {
		if owner, ok := owningUnit(p, key); ok {
			clustered[owner] = append(clustered[owner], key)
			continue
		}
		loose = append(loose, key)
	}

	var b strings.Builder
	fmt.Fprintf(&b, `"""Architecture of %s, generated by cloudcc.

Diagram as code, using https://pypi.org/project/diagrams -- rendered from the
same edges the compiler resolved, so it cannot show a resource that was not
compiled or omit one that was.

    pip install diagrams   # and graphviz
    python %s

Recompiling overwrites this file. Copy it before editing.
"""

`, opts.App, PythonFile)

	b.WriteString("from diagrams import Cluster, Diagram, Edge\n")
	for _, imp := range importsFor(resources) {
		b.WriteString(imp + "\n")
	}
	b.WriteString("\n")

	fmt.Fprintf(&b, "with Diagram(\n    %q,\n    filename=%q,\n    outformat=%q,\n    show=False,\n    direction=%q,\n):\n",
		opts.App, archPNGStem(opts.App), "png", "LR")

	vars := map[string]string{}
	for _, unit := range config.SortedKeys(clustered) {
		fmt.Fprintf(&b, "    with Cluster(%q):\n", unit)
		for _, key := range clustered[unit] {
			name := pyVar(key, vars)
			fmt.Fprintf(&b, "        %s = %s(%q)\n", name, nodeName(key.Kind), pyLabel(key))
		}
	}
	for _, key := range loose {
		name := pyVar(key, vars)
		fmt.Fprintf(&b, "    %s = %s(%q)\n", name, nodeName(key.Kind), pyLabel(key))
	}

	b.WriteString("\n")
	for _, e := range edges(p, Resources) {
		from, ok := vars[e.From.String()]
		if !ok {
			continue
		}
		to, ok := vars[e.To.String()]
		if !ok {
			continue
		}
		// A `uses` edge is data flowing at runtime; everything else is a
		// creation dependency. Drawing them alike is what turns one of these
		// pictures into a hairball, so the second kind is dimmed.
		if e.Kind == ir.EdgeUses {
			fmt.Fprintf(&b, "    %s >> Edge(label=%q) >> %s\n", from, "uses", to)
			continue
		}
		fmt.Fprintf(&b, "    %s >> Edge(color=%q, style=%q) >> %s\n", from, "gray60", "dashed", to)
	}
	return []byte(b.String())
}

// owningUnit reports which execution unit a resource expanded from, if any.
func owningUnit(p *ir.Program, key ir.Key) (string, bool) {
	for _, in := range p.Intents() {
		if in.Capability() != config.KindExecutionUnit {
			continue
		}
		for _, res := range p.ResolvedFrom(in.Key()) {
			if res.Key() == key {
				return in.Key().ID, true
			}
		}
	}
	return "", false
}

// importsFor returns the sorted import lines the drawn nodes need.
func importsFor(keys []ir.Key) []string {
	byModule := map[string]map[string]bool{}
	for _, key := range keys {
		cls := nodeClass(key.Kind)
		i := strings.LastIndex(cls, ".")
		module, name := cls[:i], cls[i+1:]
		if byModule[module] == nil {
			byModule[module] = map[string]bool{}
		}
		byModule[module][name] = true
	}

	out := make([]string, 0, len(byModule))
	for module, names := range byModule {
		sorted := make([]string, 0, len(names))
		for name := range names {
			sorted = append(sorted, name)
		}
		sort.Strings(sorted)
		out = append(out, fmt.Sprintf("from diagrams.%s import %s", module, strings.Join(sorted, ", ")))
	}
	sort.Strings(out)
	return out
}

// pyVar assigns a unique Python identifier to a resource and remembers it.
func pyVar(key ir.Key, seen map[string]string) string {
	base := "n_" + nodeID(key)
	name := base
	for i := 2; used(seen, name); i++ {
		name = fmt.Sprintf("%s_%d", base, i)
	}
	seen[key.String()] = name
	return name
}

func used(seen map[string]string, name string) bool {
	for _, v := range seen {
		if v == name {
			return true
		}
	}
	return false
}

// pyLabel is the caption under an icon: the id, and the service when the id
// alone would not say which resource this is.
func pyLabel(key ir.Key) string {
	return key.ID + "\n" + serviceName(key.Kind)
}

// archPNGStem is what the diagrams program passes as `filename`; the package
// appends the format itself.
func archPNGStem(app string) string { return app + "-architecture" }
