// Package topology renders the compiled program as a diagram.
//
// Rendering is entirely local (D12). Klotho 1 posted its graph to an
// unversioned remote endpoint to get a picture back, which meant a compile
// could fail, or leak, because of someone else's service. Here Mermaid and DOT
// are always written, and a PNG is produced only if graphviz happens to be
// installed -- with a one-line notice when it is not.
//
// The diagram is rendered from the program's own edges rather than a parallel
// structure built for drawing, so it cannot fall out of step with what was
// actually compiled.
package topology

import (
	"fmt"
	"sort"
	"strings"

	"github.com/cloudcompiler/cloudcc/internal/config"
	"github.com/cloudcompiler/cloudcc/internal/ir"
)

// View selects which layer of the IR to draw.
type View int

const (
	// Intents draws the provider-agnostic layer: what the program declared.
	Intents View = iota
	// Resources draws the concrete layer: what it resolved to.
	Resources
)

// Options controls rendering.
type Options struct {
	App  string
	View View
}

// label renders a node's caption.
//
// A resource's kind is a Pulumi type -- "aws.dynamodb", "aws.iam.role" -- and
// reading a dozen of those is how a diagram stops being worth looking at. The
// service name alone is what someone wants: the id says which resource, the
// service says what it is.
func label(key ir.Key) string {
	return key.ID + "\n" + serviceName(key.Kind)
}

// serviceName shortens a concrete resource kind to something readable, and
// leaves a capability kind alone.
func serviceName(kind string) string {
	if !strings.HasPrefix(kind, "aws.") {
		return kind
	}
	return strings.TrimPrefix(kind, "aws.")
}

// nodeID makes a key safe to use as a graph node identifier.
func nodeID(key ir.Key) string {
	var b strings.Builder
	for _, r := range key.Kind + "_" + key.ID {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}

// shape maps a node's kind to a Mermaid shape, so the picture carries some
// meaning beyond the labels.
//
// The two layers are drawn with the same vocabulary on purpose: a DynamoDB
// table is a cylinder for the same reason `persist_kv` is, so the intent
// diagram and the architecture diagram can be read side by side and the second
// one is recognisably an expansion of the first.
func shape(kind string) (open, close string) {
	if strings.HasPrefix(kind, "aws.") {
		return shape(awsCategory(kind))
	}
	switch {
	case kind == config.KindExecutionUnit:
		return "[", "]" // rectangle: compute
	case kind == config.KindExpose:
		return "([", "])" // stadium: entrypoint
	case kind == config.KindPubSub:
		return ">", "]" // flag: a channel
	case kind == config.KindConfig:
		return "{{", "}}" // hexagon: configuration
	case kind == config.KindStaticUnit:
		return "[/", "/]" // parallelogram: assets
	case config.IsPersistKind(kind):
		return "[(", ")]" // cylinder: storage
	}
	return "[", "]"
}

// edgeArrow maps an edge kind to a Mermaid arrow with a caption.
func edgeArrow(kind string) string {
	switch kind {
	case ir.EdgeUses:
		return "-->|uses|"
	case ir.EdgeExposes:
		return "-->|exposes|"
	case ir.EdgePublishes:
		return "-->|publishes|"
	case ir.EdgeSubscribes:
		return "-.->|subscribes|"
	case ir.EdgeResolvesTo:
		return "-.->|resolves to|"
	}
	return "-->"
}

// nodes returns the keys to draw for a view, sorted.
func nodes(p *ir.Program, view View) []ir.Key {
	var out []ir.Key
	if view == Intents {
		for _, in := range p.Intents() {
			out = append(out, in.Key())
		}
	} else {
		for _, res := range p.Resources() {
			out = append(out, res.Key())
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].String() < out[j].String() })
	return out
}

// edges returns the edges between drawn nodes, excluding resolves_to, which
// would double every node's connections without saying anything new.
func edges(p *ir.Program, view View) []ir.Edge {
	drawn := map[string]bool{}
	for _, key := range nodes(p, view) {
		drawn[key.String()] = true
	}
	var out []ir.Edge
	for _, e := range p.Edges() {
		if e.Kind == ir.EdgeResolvesTo {
			continue
		}
		if drawn[e.From.String()] && drawn[e.To.String()] {
			out = append(out, e)
		}
	}
	return out
}

// Mermaid renders the program as a Mermaid flowchart.
func Mermaid(p *ir.Program, opts Options) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "%%%% Architecture of %s, generated by cloudcc.\n", opts.App)
	b.WriteString("flowchart LR\n")

	for _, key := range nodes(p, opts.View) {
		open, close := shape(key.Kind)
		fmt.Fprintf(&b, "    %s%s%q%s\n", nodeID(key), open, label(key), close)
	}
	for _, e := range edges(p, opts.View) {
		fmt.Fprintf(&b, "    %s %s %s\n", nodeID(e.From), edgeArrow(e.Kind), nodeID(e.To))
	}
	return []byte(b.String())
}

// DOT renders the program in Graphviz's language.
func DOT(p *ir.Program, opts Options) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Architecture of %s, generated by cloudcc.\n", opts.App)
	fmt.Fprintf(&b, "digraph %q {\n", opts.App)
	b.WriteString("    rankdir=LR;\n")
	b.WriteString("    node [shape=box, style=rounded, fontname=\"Helvetica\"];\n")
	b.WriteString("    edge [fontname=\"Helvetica\", fontsize=10];\n")

	for _, key := range nodes(p, opts.View) {
		fmt.Fprintf(&b, "    %s [label=%q, shape=%s];\n",
			nodeID(key), strings.ReplaceAll(label(key), "\n", "\\n"), dotShape(key.Kind))
	}
	for _, e := range edges(p, opts.View) {
		style := ""
		if e.Kind == ir.EdgeSubscribes {
			style = ", style=dashed"
		}
		fmt.Fprintf(&b, "    %s -> %s [label=%q%s];\n", nodeID(e.From), nodeID(e.To), e.Kind, style)
	}
	b.WriteString("}\n")
	return []byte(b.String())
}

// awsCategory maps a concrete resource to the capability kind it looks like,
// so both diagrams share one visual vocabulary.
func awsCategory(kind string) string {
	switch kind {
	case "aws.lambda", "aws.ecs.service", "aws.ecs.task", "aws.ecs.taskdefinition":
		return config.KindExecutionUnit
	case "aws.apigatewayv2", "aws.alb":
		return config.KindExpose
	case "aws.sns", "aws.sns.subscription", "aws.sqs", "aws.kinesis":
		return config.KindPubSub
	case "aws.dynamodb", "aws.s3", "aws.rds", "aws.elasticache", "aws.memorydb",
		"aws.secretsmanager":
		return config.KindPersistKV
	case "aws.s3.website", "aws.s3.object":
		return config.KindStaticUnit
	}
	// Everything else -- roles, policies, log groups, VPC plumbing -- is
	// supporting cast, and drawn as a plain box.
	return ""
}

func dotShape(kind string) string {
	if strings.HasPrefix(kind, "aws.") {
		return dotShape(awsCategory(kind))
	}
	switch {
	case kind == config.KindExecutionUnit:
		return "box"
	case kind == config.KindExpose:
		return "ellipse"
	case kind == config.KindPubSub:
		return "cds"
	case kind == config.KindConfig:
		return "hexagon"
	case kind == config.KindStaticUnit:
		return "parallelogram"
	case config.IsPersistKind(kind):
		return "cylinder"
	}
	return "box"
}
