// Generated by cloudcc. Lambda entrypoint for execution unit "summary".
//
// Do not edit: recompiling overwrites this file.

// First, so that logging is configured before the application module is
// evaluated: ES modules evaluate their dependencies in source order.
import "./_cloudcc_runtime/logs.js";
import * as _cloudccPubsub from "./_cloudcc_runtime/pubsub.js";
import * as _cloudccRpc from "./_cloudcc_runtime/rpc.js";

const _module = await import("./src/summary.ts");

/**
 * Route the invocation to the right adapter.
 *
 * A single unit can be an HTTP handler, a topic subscriber and callable by
 * other units all at once, so the event shape decides: a call envelope goes to
 * the named function, a topic or queue delivery goes to the registered
 * subscribers, and anything else is treated as an HTTP request.
 */
export async function handler(event, context) {
  if (_cloudccRpc.isCall(event)) {
    return _cloudccRpc.dispatch(_module, event);
  }
  if (_cloudccPubsub.isDelivery(event)) {
    return _cloudccPubsub.dispatch(event);
  }
  return { unit: "summary", handled: false };
}
