// Generated by cloudcc. Container entrypoint for execution unit "reporter".
//
// Do not edit: recompiling overwrites this file.
//
// The unit's own module exports an application; it does not listen, because a
// module that listened on import could not also be wrapped for Lambda. This is
// the container's counterpart to the Lambda entry -- and to uvicorn, which
// plays exactly this role for a Python unit.
// First, so that logging is configured before the application module is
// evaluated: ES modules evaluate their dependencies in source order.
import "./_cloudcc_runtime/logs.js";
import * as _module from "./src/reporter.ts";

const app = _module.app ?? _module.default;
if (!app) {
  console.error(
    'cloudcc: src/reporter.ts exports no "app" and no default export, ' +
      "so there is nothing to serve",
  );
  process.exit(1);
}

const port = Number(process.env.PORT ?? 8080);
app.listen(port, "0.0.0.0", () => {
  console.log(`cloudcc: reporter listening on ${port}`);
});
