"""Architecture of kitchen-sink, generated by cloudcc.

Diagram as code, using https://pypi.org/project/diagrams -- rendered from the
same edges the compiler resolved, so it cannot show a resource that was not
compiled or omit one that was.

    pip install diagrams   # and graphviz
    python architecture.py

Recompiling overwrites this file. Copy it before editing.
"""

from diagrams import Cluster, Diagram, Edge
from diagrams.aws.compute import ECR, ECS, ElasticContainerServiceService, ElasticContainerServiceTask, Lambda
from diagrams.aws.database import Dynamodb, ElastiCache, RDS
from diagrams.aws.general import General
from diagrams.aws.integration import SNS
from diagrams.aws.management import CloudwatchLogs
from diagrams.aws.network import APIGateway, APIGatewayEndpoint, ELB, ElbApplicationLoadBalancer, InternetGateway, Nacl, PrivateSubnet, RouteTable, VPC
from diagrams.aws.security import IAMPermissions, IAMRole, SecretsManager
from diagrams.aws.storage import S3

with Diagram(
    "kitchen-sink",
    filename="kitchen-sink-architecture",
    outformat="png",
    show=False,
    direction="LR",
):
    with Cluster("api"):
        n_aws_cloudwatch_loggroup_api = CloudwatchLogs("api\ncloudwatch.loggroup")
        n_aws_iam_policy_api = IAMPermissions("api\niam.policy")
        n_aws_iam_role_api = IAMRole("api\niam.role")
        n_aws_lambda_api = Lambda("api\nlambda")
    with Cluster("reporter"):
        n_aws_cloudwatch_loggroup_reporter = CloudwatchLogs("reporter\ncloudwatch.loggroup")
        n_aws_ecr_reporter = ECR("reporter\necr")
        n_aws_ecs_execrole_reporter_exec = IAMRole("reporter-exec\necs.execrole")
        n_aws_ecs_service_reporter = ElasticContainerServiceService("reporter\necs.service")
        n_aws_ecs_taskdefinition_reporter = ElasticContainerServiceTask("reporter\necs.taskdefinition")
        n_aws_ecs_taskpolicy_reporter = IAMPermissions("reporter\necs.taskpolicy")
        n_aws_ecs_taskrole_reporter_task = IAMRole("reporter-task\necs.taskrole")
    n_aws_alb_listener_reporter_web = ELB("reporter-web\nalb.listener")
    n_aws_alb_targetgroup_reporter_web = ELB("reporter-web\nalb.targetgroup")
    n_aws_alb_reporter_web = ElbApplicationLoadBalancer("reporter-web\nalb")
    n_aws_apigatewayv2_integration_shop_api = APIGatewayEndpoint("shop-api\napigatewayv2.integration")
    n_aws_apigatewayv2_route_shop_api = APIGatewayEndpoint("shop-api\napigatewayv2.route")
    n_aws_apigatewayv2_stage_shop_api = APIGatewayEndpoint("shop-api\napigatewayv2.stage")
    n_aws_apigatewayv2_shop_api = APIGateway("shop-api\napigatewayv2")
    n_aws_availabilityzones_network = General("network\navailabilityzones")
    n_aws_dynamodb_catalogue = Dynamodb("catalogue\ndynamodb")
    n_aws_ecs_cluster_cluster = ECS("cluster\necs.cluster")
    n_aws_elasticache_itemCache = ElastiCache("itemCache\nelasticache")
    n_aws_lambda_permission_shop_api = IAMPermissions("shop-api\nlambda.permission")
    n_aws_rds_shopdb = RDS("shopdb\nrds")
    n_aws_s3_itemDocs = S3("itemDocs\ns3")
    n_aws_secretsmanager_signingKey = SecretsManager("signingKey\nsecretsmanager")
    n_aws_sns_itemEvents = SNS("itemEvents\nsns")
    n_aws_subnetgroup_elasticache = General("elasticache\nsubnetgroup")
    n_aws_subnetgroup_rds = General("rds\nsubnetgroup")
    n_aws_vpc_gateway_network = InternetGateway("network\nvpc.gateway")
    n_aws_vpc_routeassoc_network_0 = RouteTable("network-0\nvpc.routeassoc")
    n_aws_vpc_routeassoc_network_1 = RouteTable("network-1\nvpc.routeassoc")
    n_aws_vpc_routetable_network = RouteTable("network\nvpc.routetable")
    n_aws_vpc_securitygroup_network = Nacl("network\nvpc.securitygroup")
    n_aws_vpc_subnet_network_0 = PrivateSubnet("network-0\nvpc.subnet")
    n_aws_vpc_subnet_network_1 = PrivateSubnet("network-1\nvpc.subnet")
    n_aws_vpc_network = VPC("network\nvpc")

    n_aws_alb_listener_reporter_web >> Edge(color="gray60", style="dashed") >> n_aws_alb_targetgroup_reporter_web
    n_aws_alb_listener_reporter_web >> Edge(color="gray60", style="dashed") >> n_aws_alb_reporter_web
    n_aws_alb_targetgroup_reporter_web >> Edge(color="gray60", style="dashed") >> n_aws_vpc_network
    n_aws_alb_reporter_web >> Edge(color="gray60", style="dashed") >> n_aws_vpc_securitygroup_network
    n_aws_alb_reporter_web >> Edge(color="gray60", style="dashed") >> n_aws_vpc_subnet_network_0
    n_aws_alb_reporter_web >> Edge(color="gray60", style="dashed") >> n_aws_vpc_subnet_network_1
    n_aws_apigatewayv2_integration_shop_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_shop_api
    n_aws_apigatewayv2_integration_shop_api >> Edge(color="gray60", style="dashed") >> n_aws_lambda_api
    n_aws_apigatewayv2_route_shop_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_integration_shop_api
    n_aws_apigatewayv2_route_shop_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_shop_api
    n_aws_apigatewayv2_stage_shop_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_route_shop_api
    n_aws_apigatewayv2_stage_shop_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_shop_api
    n_aws_ecs_service_reporter >> Edge(color="gray60", style="dashed") >> n_aws_alb_listener_reporter_web
    n_aws_ecs_service_reporter >> Edge(color="gray60", style="dashed") >> n_aws_alb_targetgroup_reporter_web
    n_aws_ecs_service_reporter >> Edge(color="gray60", style="dashed") >> n_aws_ecs_cluster_cluster
    n_aws_ecs_service_reporter >> Edge(color="gray60", style="dashed") >> n_aws_ecs_taskdefinition_reporter
    n_aws_ecs_service_reporter >> Edge(color="gray60", style="dashed") >> n_aws_vpc_securitygroup_network
    n_aws_ecs_service_reporter >> Edge(color="gray60", style="dashed") >> n_aws_vpc_subnet_network_0
    n_aws_ecs_service_reporter >> Edge(color="gray60", style="dashed") >> n_aws_vpc_subnet_network_1
    n_aws_ecs_taskdefinition_reporter >> Edge(color="gray60", style="dashed") >> n_aws_cloudwatch_loggroup_reporter
    n_aws_ecs_taskdefinition_reporter >> Edge(color="gray60", style="dashed") >> n_aws_ecr_reporter
    n_aws_ecs_taskdefinition_reporter >> Edge(color="gray60", style="dashed") >> n_aws_ecs_execrole_reporter_exec
    n_aws_ecs_taskdefinition_reporter >> Edge(color="gray60", style="dashed") >> n_aws_ecs_taskrole_reporter_task
    n_aws_ecs_taskpolicy_reporter >> Edge(color="gray60", style="dashed") >> n_aws_dynamodb_catalogue
    n_aws_ecs_taskpolicy_reporter >> Edge(color="gray60", style="dashed") >> n_aws_ecs_taskrole_reporter_task
    n_aws_ecs_taskpolicy_reporter >> Edge(color="gray60", style="dashed") >> n_aws_rds_shopdb
    n_aws_ecs_taskpolicy_reporter >> Edge(color="gray60", style="dashed") >> n_aws_s3_itemDocs
    n_aws_ecs_taskpolicy_reporter >> Edge(color="gray60", style="dashed") >> n_aws_secretsmanager_signingKey
    n_aws_elasticache_itemCache >> Edge(color="gray60", style="dashed") >> n_aws_subnetgroup_elasticache
    n_aws_elasticache_itemCache >> Edge(color="gray60", style="dashed") >> n_aws_vpc_securitygroup_network
    n_aws_iam_policy_api >> Edge(color="gray60", style="dashed") >> n_aws_dynamodb_catalogue
    n_aws_iam_policy_api >> Edge(color="gray60", style="dashed") >> n_aws_iam_role_api
    n_aws_iam_policy_api >> Edge(color="gray60", style="dashed") >> n_aws_rds_shopdb
    n_aws_iam_policy_api >> Edge(color="gray60", style="dashed") >> n_aws_s3_itemDocs
    n_aws_iam_policy_api >> Edge(color="gray60", style="dashed") >> n_aws_secretsmanager_signingKey
    n_aws_iam_policy_api >> Edge(color="gray60", style="dashed") >> n_aws_sns_itemEvents
    n_aws_lambda_permission_shop_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_shop_api
    n_aws_lambda_permission_shop_api >> Edge(color="gray60", style="dashed") >> n_aws_lambda_api
    n_aws_lambda_api >> Edge(color="gray60", style="dashed") >> n_aws_cloudwatch_loggroup_api
    n_aws_lambda_api >> Edge(color="gray60", style="dashed") >> n_aws_iam_role_api
    n_aws_rds_shopdb >> Edge(color="gray60", style="dashed") >> n_aws_subnetgroup_rds
    n_aws_rds_shopdb >> Edge(color="gray60", style="dashed") >> n_aws_vpc_securitygroup_network
    n_aws_subnetgroup_elasticache >> Edge(color="gray60", style="dashed") >> n_aws_vpc_subnet_network_0
    n_aws_subnetgroup_elasticache >> Edge(color="gray60", style="dashed") >> n_aws_vpc_subnet_network_1
    n_aws_subnetgroup_rds >> Edge(color="gray60", style="dashed") >> n_aws_vpc_subnet_network_0
    n_aws_subnetgroup_rds >> Edge(color="gray60", style="dashed") >> n_aws_vpc_subnet_network_1
    n_aws_vpc_gateway_network >> Edge(color="gray60", style="dashed") >> n_aws_vpc_network
    n_aws_vpc_routeassoc_network_0 >> Edge(color="gray60", style="dashed") >> n_aws_vpc_routetable_network
    n_aws_vpc_routeassoc_network_0 >> Edge(color="gray60", style="dashed") >> n_aws_vpc_subnet_network_0
    n_aws_vpc_routeassoc_network_1 >> Edge(color="gray60", style="dashed") >> n_aws_vpc_routetable_network
    n_aws_vpc_routeassoc_network_1 >> Edge(color="gray60", style="dashed") >> n_aws_vpc_subnet_network_1
    n_aws_vpc_routetable_network >> Edge(color="gray60", style="dashed") >> n_aws_vpc_gateway_network
    n_aws_vpc_routetable_network >> Edge(color="gray60", style="dashed") >> n_aws_vpc_network
    n_aws_vpc_securitygroup_network >> Edge(color="gray60", style="dashed") >> n_aws_vpc_network
    n_aws_vpc_subnet_network_0 >> Edge(color="gray60", style="dashed") >> n_aws_availabilityzones_network
    n_aws_vpc_subnet_network_0 >> Edge(color="gray60", style="dashed") >> n_aws_vpc_network
    n_aws_vpc_subnet_network_1 >> Edge(color="gray60", style="dashed") >> n_aws_availabilityzones_network
    n_aws_vpc_subnet_network_1 >> Edge(color="gray60", style="dashed") >> n_aws_vpc_network
    n_aws_ecs_service_reporter >> Edge(label="uses") >> n_aws_dynamodb_catalogue
    n_aws_ecs_service_reporter >> Edge(label="uses") >> n_aws_elasticache_itemCache
    n_aws_ecs_service_reporter >> Edge(label="uses") >> n_aws_rds_shopdb
    n_aws_ecs_service_reporter >> Edge(label="uses") >> n_aws_s3_itemDocs
    n_aws_ecs_service_reporter >> Edge(label="uses") >> n_aws_secretsmanager_signingKey
    n_aws_ecs_service_reporter >> Edge(label="uses") >> n_aws_sns_itemEvents
    n_aws_ecs_taskdefinition_reporter >> Edge(label="uses") >> n_aws_dynamodb_catalogue
    n_aws_ecs_taskdefinition_reporter >> Edge(label="uses") >> n_aws_elasticache_itemCache
    n_aws_ecs_taskdefinition_reporter >> Edge(label="uses") >> n_aws_rds_shopdb
    n_aws_ecs_taskdefinition_reporter >> Edge(label="uses") >> n_aws_s3_itemDocs
    n_aws_ecs_taskdefinition_reporter >> Edge(label="uses") >> n_aws_secretsmanager_signingKey
    n_aws_ecs_taskdefinition_reporter >> Edge(label="uses") >> n_aws_sns_itemEvents
    n_aws_lambda_api >> Edge(label="uses") >> n_aws_dynamodb_catalogue
    n_aws_lambda_api >> Edge(label="uses") >> n_aws_elasticache_itemCache
    n_aws_lambda_api >> Edge(label="uses") >> n_aws_rds_shopdb
    n_aws_lambda_api >> Edge(label="uses") >> n_aws_s3_itemDocs
    n_aws_lambda_api >> Edge(label="uses") >> n_aws_secretsmanager_signingKey
    n_aws_lambda_api >> Edge(label="uses") >> n_aws_sns_itemEvents
