"""Architecture of kitchen-sink, generated by cloudcc.

Diagram as code, using https://pypi.org/project/diagrams -- one icon per
capability, showing the service each one resolved to and how the program said
they are connected.

The supporting cast is deliberately absent: roles, policies, log groups and an
HTTP API's internal wiring all exist, and all of them are in architecture.mmd
and architecture.dot. This file answers "what is this system", not "what will
exist in the account".

    pip install diagrams   # and graphviz
    python architecture.py

Recompiling overwrites this file. Copy it before editing.
"""

from diagrams import Diagram, Edge
from diagrams.aws.compute import ElasticContainerServiceService, Lambda
from diagrams.aws.database import Dynamodb, ElastiCache, RDS
from diagrams.aws.integration import SNS
from diagrams.aws.network import APIGateway, ElbApplicationLoadBalancer
from diagrams.aws.security import SecretsManager
from diagrams.aws.storage import S3

with Diagram(
    "kitchen-sink",
    filename="kitchen-sink-architecture",
    outformat="png",
    show=False,
    direction="LR",
):
    n_execution_unit_api = Lambda("api\nLambda")
    n_execution_unit_auditor = Lambda("auditor\nLambda")
    n_execution_unit_reporter = ElasticContainerServiceService("reporter\nFargate")
    n_expose_reporter_web = ElbApplicationLoadBalancer("reporter-web\nLoad Balancer")
    n_expose_shop_api = APIGateway("shop-api\nAPI Gateway")
    n_persist_fs_itemDocs = S3("itemDocs\nS3")
    n_persist_kv_catalogue = Dynamodb("catalogue\nDynamoDB")
    n_persist_orm_shopdb = RDS("shopdb\nRDS")
    n_persist_redis_itemCache = ElastiCache("itemCache\nElastiCache")
    n_persist_secret_signingKey = SecretsManager("signingKey\nSecrets Manager")
    n_pubsub_itemEvents = SNS("itemEvents\nSNS")

    n_expose_reporter_web >> n_execution_unit_reporter
    n_expose_shop_api >> n_execution_unit_api
    n_execution_unit_api >> Edge(label="publishes") >> n_pubsub_itemEvents
    n_pubsub_itemEvents >> Edge(label="subscribes", style="dashed") >> n_execution_unit_auditor
    n_execution_unit_api >> n_persist_fs_itemDocs
    n_execution_unit_api >> n_persist_kv_catalogue
    n_execution_unit_api >> n_persist_orm_shopdb
    n_execution_unit_api >> n_persist_redis_itemCache
    n_execution_unit_api >> n_persist_secret_signingKey
    n_execution_unit_auditor >> n_persist_fs_itemDocs
    n_execution_unit_auditor >> n_persist_kv_catalogue
    n_execution_unit_auditor >> n_persist_orm_shopdb
    n_execution_unit_auditor >> n_persist_redis_itemCache
    n_execution_unit_auditor >> n_persist_secret_signingKey
    n_execution_unit_reporter >> n_persist_fs_itemDocs
    n_execution_unit_reporter >> n_persist_kv_catalogue
    n_execution_unit_reporter >> n_persist_orm_shopdb
    n_execution_unit_reporter >> n_persist_redis_itemCache
    n_execution_unit_reporter >> n_persist_secret_signingKey
