// Generated by cc for application "kitchen-sink". Do not edit: recompiling overwrites
// this file. To change what is generated, edit cc.yaml in your source tree.
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

// Secret configuration values come from the encrypted stack config.
// Set them with: pulumi config set --secret cc:<name> <value>
const ccConfig = new pulumi.Config("cc");
const stripeKeySecret = ccConfig.requireSecret("stripe_key");

export const shopApiApi = new aws.apigatewayv2.Api("shop-api", {
    name: "kitchen-sink-shop-api",
    protocolType: "HTTP",
});

export const networkZones = aws.getAvailabilityZonesOutput({
    state: "available",
});

export const apiLogs = new aws.cloudwatch.LogGroup("api", {
    name: "/aws/lambda/kitchen-sink-api",
    retentionInDays: 14,
});

export const reporterLogs = new aws.cloudwatch.LogGroup("reporter", {
    name: "/ecs/kitchen-sink-reporter",
    retentionInDays: 14,
});

export const catalogueTable = new aws.dynamodb.Table("catalogue", {
    attributes: [
        {
            name: "id",
            type: "S",
        },
    ],
    billingMode: "PAY_PER_REQUEST",
    hashKey: "id",
    name: "kitchen-sink-catalogue",
});

export const reporterRepo = new aws.ecr.Repository("reporter", {
    forceDelete: true,
    name: "kitchen-sink-reporter",
});

export const clusterCluster = new aws.ecs.Cluster("cluster", {
    name: "kitchen-sink-cluster",
});

export const reporterExecRole = new aws.iam.Role("reporter-exec", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "ecs-tasks.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy",
    ],
    name: "kitchen-sink-reporter-exec",
});

export const reporterTaskRole = new aws.iam.Role("reporter-task", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "ecs-tasks.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    name: "kitchen-sink-reporter-task",
});

export const apiRole = new aws.iam.Role("api", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "kitchen-sink-api-role",
});

export const itemDocsBucket = new aws.s3.BucketV2("itemDocs", {
    bucket: "kitchen-sink-itemdocs",
    forceDestroy: true,
});

export const signingKeySecret = new aws.secretsmanager.Secret("signingKey", {
    name: "kitchen-sink-signingKey",
    recoveryWindowInDays: 0,
});

export const itemEventsTopic = new aws.sns.Topic("itemEvents", {
    name: "kitchen-sink-itemEvents",
});

export const networkVpc = new aws.ec2.Vpc("network", {
    cidrBlock: "10.0.0.0/16",
    enableDnsHostnames: true,
    enableDnsSupport: true,
    tags: {
        Name: "kitchen-sink-network",
    },
});

export const reporterWebTargetGroup = new aws.lb.TargetGroup("reporter-web", {
    healthCheck: {
        matcher: "200-399",
        path: "/health",
    },
    name: "kitchen-sink-reporter-web-tg",
    port: 8080,
    protocol: "HTTP",
    targetType: "ip",
    vpcId: networkVpc.id,
});

export const networkGateway = new aws.ec2.InternetGateway("network", {
    vpcId: networkVpc.id,
});

export const networkRoutes = new aws.ec2.RouteTable("network", {
    routes: [
        {
            cidrBlock: "0.0.0.0/0",
            gatewayId: networkGateway.id,
        },
    ],
    vpcId: networkVpc.id,
});

export const networkSecurityGroup = new aws.ec2.SecurityGroup("network", {
    description: "Managed by cc: traffic between compiled units and their datastores",
    egress: [
        {
            cidrBlocks: [
                "0.0.0.0/0",
            ],
            fromPort: 0,
            protocol: "-1",
            toPort: 0,
        },
    ],
    ingress: [
        {
            cidrBlocks: [
                "0.0.0.0/0",
            ],
            description: "inbound from the load balancer and within the VPC",
            fromPort: 0,
            protocol: "-1",
            toPort: 0,
        },
    ],
    vpcId: networkVpc.id,
});

export const network0Subnet = new aws.ec2.Subnet("network-0", {
    availabilityZone: networkZones.names.apply(n => n[0]),
    cidrBlock: "10.0.0.0/24",
    mapPublicIpOnLaunch: true,
    tags: {
        Name: "kitchen-sink-network-0",
    },
    vpcId: networkVpc.id,
});

export const network0RouteAssoc = new aws.ec2.RouteTableAssociation("network-0", {
    routeTableId: networkRoutes.id,
    subnetId: network0Subnet.id,
});

export const network1Subnet = new aws.ec2.Subnet("network-1", {
    availabilityZone: networkZones.names.apply(n => n[1]),
    cidrBlock: "10.0.1.0/24",
    mapPublicIpOnLaunch: true,
    tags: {
        Name: "kitchen-sink-network-1",
    },
    vpcId: networkVpc.id,
});

export const reporterWebAlb = new aws.lb.LoadBalancer("reporter-web", {
    internal: false,
    loadBalancerType: "application",
    name: "kitchen-sink-reporter-web",
    securityGroups: [
        networkSecurityGroup.id,
    ],
    subnets: [
        network0Subnet.id,
        network1Subnet.id,
    ],
});

export const reporterWebListener = new aws.lb.Listener("reporter-web", {
    defaultActions: [
        {
            targetGroupArn: reporterWebTargetGroup.arn,
            type: "forward",
        },
    ],
    loadBalancerArn: reporterWebAlb.arn,
    port: 80,
    protocol: "HTTP",
});

export const elasticacheSubnetGroup = new aws.elasticache.SubnetGroup("elasticache", {
    name: "kitchen-sink-elasticache",
    subnetIds: [
        network0Subnet.id,
        network1Subnet.id,
    ],
});

export const itemCacheCache = new aws.elasticache.Cluster("itemCache", {
    clusterId: "kitchen-sink-itemcache",
    engine: "redis",
    nodeType: "cache.t4g.micro",
    numCacheNodes: 1,
    port: 6379,
    securityGroupIds: [
        networkSecurityGroup.id,
    ],
    subnetGroupName: elasticacheSubnetGroup.name,
});

export const rdsSubnetGroup = new aws.rds.SubnetGroup("rds", {
    name: "kitchen-sink-rds",
    subnetIds: [
        network0Subnet.id,
        network1Subnet.id,
    ],
});

export const shopdbDb = new aws.rds.Instance("shopdb", {
    allocatedStorage: 20,
    dbName: "shopdb",
    dbSubnetGroupName: rdsSubnetGroup.name,
    engine: "postgres",
    identifier: "kitchen-sink-shopdb",
    instanceClass: "db.t4g.micro",
    manageMasterUserPassword: true,
    publiclyAccessible: false,
    skipFinalSnapshot: true,
    username: "ccadmin",
    vpcSecurityGroupIds: [
        networkSecurityGroup.id,
    ],
});

const reporterEnv: { [key: string]: pulumi.Input<string> } = {
    CC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CC_AWS_ENDPOINT_URL ?? ""}`,
    CC_FS_ITEMDOCS_BUCKET: pulumi.interpolate`${itemDocsBucket.bucket}`,
    CC_KV_CATALOGUE_TABLE: pulumi.interpolate`${catalogueTable.name}`,
    CC_ORM_SHOPDB_SECRET_ARN: pulumi.interpolate`${shopdbDb.masterUserSecrets.apply(s => s[0].secretArn)}`,
    CC_ORM_SHOPDB_URL: pulumi.interpolate`postgresql://ccadmin@${shopdbDb.address}:${shopdbDb.port}/shopdb`,
    CC_REDIS_ITEMCACHE_ENDPOINT: pulumi.interpolate`${itemCacheCache.cacheNodes.apply(n => n[0].address)}`,
    CC_REDIS_ITEMCACHE_PORT: "6379",
    CC_REDIS_ITEMCACHE_TLS: "false",
    CC_SECRET_SIGNINGKEY_ARN: pulumi.interpolate`${signingKeySecret.arn}`,
    CC_TOPIC_ITEMEVENTS_ARN: pulumi.interpolate`${itemEventsTopic.arn}`,
};

export const reporterTask = new aws.ecs.TaskDefinition("reporter", {
    containerDefinitions: pulumi.jsonStringify([{
    environment: Object.entries(reporterEnv).map(([name, value]) => ({ name, value })),
    image: pulumi.interpolate`${reporterRepo.repositoryUrl}:latest`,
    logConfiguration: {
        logDriver: "awslogs",
        options: {
            "awslogs-group": reporterLogs.name,
            "awslogs-region": aws.config.region,
            "awslogs-stream-prefix": "reporter",
        },
    },
    name: "reporter",
    portMappings: [
        {
            containerPort: 8080,
            protocol: "tcp",
        },
    ],
}]),
    cpu: "256",
    executionRoleArn: reporterExecRole.arn,
    family: "kitchen-sink-reporter",
    memory: "512",
    networkMode: "awsvpc",
    requiresCompatibilities: [
        "FARGATE",
    ],
    taskRoleArn: reporterTaskRole.arn,
});

export const reporterService = new aws.ecs.Service("reporter", {
    cluster: clusterCluster.id,
    desiredCount: 1,
    launchType: "FARGATE",
    loadBalancers: [
        {
            containerName: "reporter",
            containerPort: 8080,
            targetGroupArn: reporterWebTargetGroup.arn,
        },
    ],
    name: "kitchen-sink-reporter",
    networkConfiguration: {
        assignPublicIp: true,
        securityGroups: [
            networkSecurityGroup.id,
        ],
        subnets: [
            network0Subnet.id,
            network1Subnet.id,
        ],
    },
    taskDefinition: reporterTask.arn,
});

export const reporterPolicy = new aws.iam.RolePolicy("reporter", {
    name: "kitchen-sink-reporter-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
            ],
            Effect: "Allow",
            Resource: [
                itemDocsBucket.arn,
                pulumi.interpolate`${itemDocsBucket.arn}/*`,
            ],
        },
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                catalogueTable.arn,
                pulumi.interpolate`${catalogueTable.arn}/index/*`,
            ],
        },
        {
            Action: [
                "secretsmanager:GetSecretValue",
            ],
            Effect: "Allow",
            Resource: [
                shopdbDb.masterUserSecrets.apply(s => s[0].secretArn),
            ],
        },
        {
            Action: [
                "secretsmanager:GetSecretValue",
                "secretsmanager:PutSecretValue",
            ],
            Effect: "Allow",
            Resource: [
                signingKeySecret.arn,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: reporterTaskRole.id,
});

export const apiPolicy = new aws.iam.RolePolicy("api", {
    name: "kitchen-sink-api-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
            ],
            Effect: "Allow",
            Resource: [
                itemDocsBucket.arn,
                pulumi.interpolate`${itemDocsBucket.arn}/*`,
            ],
        },
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                catalogueTable.arn,
                pulumi.interpolate`${catalogueTable.arn}/index/*`,
            ],
        },
        {
            Action: [
                "secretsmanager:GetSecretValue",
            ],
            Effect: "Allow",
            Resource: [
                shopdbDb.masterUserSecrets.apply(s => s[0].secretArn),
            ],
        },
        {
            Action: [
                "secretsmanager:GetSecretValue",
                "secretsmanager:PutSecretValue",
            ],
            Effect: "Allow",
            Resource: [
                signingKeySecret.arn,
            ],
        },
        {
            Action: [
                "sns:Publish",
            ],
            Effect: "Allow",
            Resource: [
                itemEventsTopic.arn,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: apiRole.id,
});

const apiEnv: { [key: string]: pulumi.Input<string> } = {
    CC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CC_AWS_ENDPOINT_URL ?? ""}`,
    CC_CONFIG_LOG_LEVEL: "info",
    CC_CONFIG_STRIPE_KEY: pulumi.interpolate`${stripeKeySecret}`,
    CC_FS_ITEMDOCS_BUCKET: pulumi.interpolate`${itemDocsBucket.bucket}`,
    CC_KV_CATALOGUE_TABLE: pulumi.interpolate`${catalogueTable.name}`,
    CC_ORM_SHOPDB_SECRET_ARN: pulumi.interpolate`${shopdbDb.masterUserSecrets.apply(s => s[0].secretArn)}`,
    CC_ORM_SHOPDB_URL: pulumi.interpolate`postgresql://ccadmin@${shopdbDb.address}:${shopdbDb.port}/shopdb`,
    CC_REDIS_ITEMCACHE_ENDPOINT: pulumi.interpolate`${itemCacheCache.cacheNodes.apply(n => n[0].address)}`,
    CC_REDIS_ITEMCACHE_PORT: "6379",
    CC_REDIS_ITEMCACHE_TLS: "false",
    CC_SECRET_SIGNINGKEY_ARN: pulumi.interpolate`${signingKeySecret.arn}`,
    CC_TOPIC_ITEMEVENTS_ARN: pulumi.interpolate`${itemEventsTopic.arn}`,
};

export const apiFn = new aws.lambda.Function("api", {
    code: new pulumi.asset.FileArchive("build/api.zip"),
    environment: { variables: apiEnv },
    handler: "cc_lambda_entry.handler",
    memorySize: 512,
    name: "kitchen-sink-api",
    role: apiRole.arn,
    runtime: "python3.12",
    timeout: 30,
});

export const shopApiIntegration = new aws.apigatewayv2.Integration("shop-api", {
    apiId: shopApiApi.id,
    integrationMethod: "POST",
    integrationType: "AWS_PROXY",
    integrationUri: apiFn.arn,
    payloadFormatVersion: "2.0",
});

export const shopApiRoute = new aws.apigatewayv2.Route("shop-api", {
    apiId: shopApiApi.id,
    routeKey: "$default",
    target: pulumi.interpolate`integrations/${shopApiIntegration.id}`,
});

export const shopApiStage = new aws.apigatewayv2.Stage("shop-api", {
    apiId: shopApiApi.id,
    autoDeploy: true,
    name: "$default",
});

export const shopApiPermission = new aws.lambda.Permission("shop-api", {
    action: "lambda:InvokeFunction",
    function: apiFn.name,
    principal: "apigateway.amazonaws.com",
    sourceArn: pulumi.interpolate`${shopApiApi.executionArn}/*/*`,
});

export const network1RouteAssoc = new aws.ec2.RouteTableAssociation("network-1", {
    routeTableId: networkRoutes.id,
    subnetId: network1Subnet.id,
});

// Stack outputs. Every environment binding is exported under the exact
// name the runtime shims read, so a compiled unit can be run locally with:
//   eval "$(pulumi output --json | jq -r 'to_entries[]|"export \(.key)=\(.value)"')"
export const CC_ECR_REPORTER_URL = pulumi.interpolate`${reporterRepo.repositoryUrl}`;
export const CC_FS_ITEMDOCS_BUCKET = pulumi.interpolate`${itemDocsBucket.bucket}`;
export const CC_GATEWAY_REPORTER_WEB_URL = pulumi.interpolate`http://${reporterWebAlb.dnsName}`;
export const CC_GATEWAY_SHOP_API_URL = pulumi.interpolate`${shopApiApi.apiEndpoint}`;
export const CC_KV_CATALOGUE_TABLE = pulumi.interpolate`${catalogueTable.name}`;
export const CC_ORM_SHOPDB_SECRET_ARN = pulumi.interpolate`${shopdbDb.masterUserSecrets.apply(s => s[0].secretArn)}`;
export const CC_ORM_SHOPDB_URL = pulumi.interpolate`postgresql://ccadmin@${shopdbDb.address}:${shopdbDb.port}/shopdb`;
export const CC_REDIS_ITEMCACHE_ENDPOINT = pulumi.interpolate`${itemCacheCache.cacheNodes.apply(n => n[0].address)}`;
export const CC_REDIS_ITEMCACHE_PORT = "6379";
export const CC_REDIS_ITEMCACHE_TLS = "false";
export const CC_SECRET_SIGNINGKEY_ARN = pulumi.interpolate`${signingKeySecret.arn}`;
export const CC_TOPIC_ITEMEVENTS_ARN = pulumi.interpolate`${itemEventsTopic.arn}`;
export const shopApiUrl = shopApiApi.apiEndpoint;
