"""Architecture of petstore-multi, generated by cloudcc.

Diagram as code, using https://pypi.org/project/diagrams -- one icon per
capability, showing the service each one resolved to and how the program said
they are connected.

The supporting cast is deliberately absent: roles, policies, log groups and an
HTTP API's internal wiring all exist, and all of them are in architecture.mmd
and architecture.dot. This file answers "what is this system", not "what will
exist in the account".

    pip install diagrams   # and graphviz
    python architecture.py

Recompiling overwrites this file. Copy it before editing.
"""

from diagrams import Diagram, Edge
from diagrams.aws.compute import Lambda
from diagrams.aws.database import Dynamodb
from diagrams.aws.integration import SNS
from diagrams.aws.network import APIGateway
from diagrams.aws.storage import S3, SimpleStorageServiceS3BucketWithObjects

with Diagram(
    "petstore-multi",
    filename="petstore-multi-architecture",
    outformat="png",
    show=False,
    direction="LR",
):
    n_execution_unit_api = Lambda("api\nLambda")
    n_execution_unit_worker = Lambda("worker\nLambda")
    n_expose_pet_api = APIGateway("pet-api\nAPI Gateway")
    n_persist_fs_petAudit = S3("petAudit\nS3")
    n_persist_kv_petsByOwner = Dynamodb("petsByOwner\nDynamoDB")
    n_pubsub_petEvents = SNS("petEvents\nSNS")
    n_static_unit_petstore_site = SimpleStorageServiceS3BucketWithObjects("petstore-site\nS3 website")

    n_expose_pet_api >> n_execution_unit_api
    n_execution_unit_api >> Edge(label="publishes") >> n_pubsub_petEvents
    n_pubsub_petEvents >> Edge(label="subscribes", style="dashed") >> n_execution_unit_worker
    n_execution_unit_api >> n_persist_kv_petsByOwner
    n_execution_unit_worker >> n_persist_fs_petAudit
    n_execution_unit_worker >> n_persist_kv_petsByOwner
