"""Architecture of petstore-multi, generated by cloudcc.

Diagram as code, using https://pypi.org/project/diagrams -- rendered from the
same edges the compiler resolved, so it cannot show a resource that was not
compiled or omit one that was.

    pip install diagrams   # and graphviz
    python architecture.py

Recompiling overwrites this file. Copy it before editing.
"""

from diagrams import Cluster, Diagram, Edge
from diagrams.aws.compute import Lambda
from diagrams.aws.database import Dynamodb
from diagrams.aws.integration import EventResource, SNS
from diagrams.aws.management import CloudwatchLogs
from diagrams.aws.network import APIGateway, APIGatewayEndpoint
from diagrams.aws.security import IAMPermissions, IAMRole
from diagrams.aws.storage import S3, SimpleStorageServiceS3BucketWithObjects, SimpleStorageServiceS3Object

with Diagram(
    "petstore-multi",
    filename="petstore-multi-architecture",
    outformat="png",
    show=False,
    direction="LR",
):
    with Cluster("api"):
        n_aws_cloudwatch_loggroup_api = CloudwatchLogs("api\ncloudwatch.loggroup")
        n_aws_iam_policy_api = IAMPermissions("api\niam.policy")
        n_aws_iam_role_api = IAMRole("api\niam.role")
        n_aws_lambda_api = Lambda("api\nlambda")
    with Cluster("worker"):
        n_aws_cloudwatch_loggroup_worker = CloudwatchLogs("worker\ncloudwatch.loggroup")
        n_aws_iam_policy_worker = IAMPermissions("worker\niam.policy")
        n_aws_iam_role_worker = IAMRole("worker\niam.role")
        n_aws_lambda_worker = Lambda("worker\nlambda")
    n_aws_apigatewayv2_integration_pet_api = APIGatewayEndpoint("pet-api\napigatewayv2.integration")
    n_aws_apigatewayv2_route_pet_api = APIGatewayEndpoint("pet-api\napigatewayv2.route")
    n_aws_apigatewayv2_stage_pet_api = APIGatewayEndpoint("pet-api\napigatewayv2.stage")
    n_aws_apigatewayv2_pet_api = APIGateway("pet-api\napigatewayv2")
    n_aws_dynamodb_petsByOwner = Dynamodb("petsByOwner\ndynamodb")
    n_aws_lambda_permission_pet_api = IAMPermissions("pet-api\nlambda.permission")
    n_aws_lambda_permission_worker_petEvents_sns = IAMPermissions("worker-petEvents-sns\nlambda.permission")
    n_aws_s3_object_petstore_site_index_html = SimpleStorageServiceS3Object("petstore-site/index.html\ns3.object")
    n_aws_s3_object_petstore_site_style_css = SimpleStorageServiceS3Object("petstore-site/style.css\ns3.object")
    n_aws_s3_website_petstore_site = SimpleStorageServiceS3BucketWithObjects("petstore-site\ns3.website")
    n_aws_s3_petAudit = S3("petAudit\ns3")
    n_aws_s3_petstore_site = S3("petstore-site\ns3")
    n_aws_sns_subscription_worker_petEvents = EventResource("worker-petEvents\nsns.subscription")
    n_aws_sns_petEvents = SNS("petEvents\nsns")

    n_aws_apigatewayv2_integration_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_pet_api
    n_aws_apigatewayv2_integration_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_lambda_api
    n_aws_apigatewayv2_route_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_integration_pet_api
    n_aws_apigatewayv2_route_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_pet_api
    n_aws_apigatewayv2_stage_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_route_pet_api
    n_aws_apigatewayv2_stage_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_pet_api
    n_aws_iam_policy_api >> Edge(color="gray60", style="dashed") >> n_aws_dynamodb_petsByOwner
    n_aws_iam_policy_api >> Edge(color="gray60", style="dashed") >> n_aws_iam_role_api
    n_aws_iam_policy_api >> Edge(color="gray60", style="dashed") >> n_aws_sns_petEvents
    n_aws_iam_policy_worker >> Edge(color="gray60", style="dashed") >> n_aws_dynamodb_petsByOwner
    n_aws_iam_policy_worker >> Edge(color="gray60", style="dashed") >> n_aws_iam_role_worker
    n_aws_iam_policy_worker >> Edge(color="gray60", style="dashed") >> n_aws_s3_petAudit
    n_aws_lambda_permission_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_apigatewayv2_pet_api
    n_aws_lambda_permission_pet_api >> Edge(color="gray60", style="dashed") >> n_aws_lambda_api
    n_aws_lambda_permission_worker_petEvents_sns >> Edge(color="gray60", style="dashed") >> n_aws_lambda_worker
    n_aws_lambda_permission_worker_petEvents_sns >> Edge(color="gray60", style="dashed") >> n_aws_sns_petEvents
    n_aws_lambda_api >> Edge(color="gray60", style="dashed") >> n_aws_cloudwatch_loggroup_api
    n_aws_lambda_api >> Edge(color="gray60", style="dashed") >> n_aws_iam_role_api
    n_aws_lambda_worker >> Edge(color="gray60", style="dashed") >> n_aws_cloudwatch_loggroup_worker
    n_aws_lambda_worker >> Edge(color="gray60", style="dashed") >> n_aws_iam_role_worker
    n_aws_s3_object_petstore_site_index_html >> Edge(color="gray60", style="dashed") >> n_aws_s3_petstore_site
    n_aws_s3_object_petstore_site_style_css >> Edge(color="gray60", style="dashed") >> n_aws_s3_petstore_site
    n_aws_s3_website_petstore_site >> Edge(color="gray60", style="dashed") >> n_aws_s3_petstore_site
    n_aws_sns_subscription_worker_petEvents >> Edge(color="gray60", style="dashed") >> n_aws_lambda_worker
    n_aws_sns_subscription_worker_petEvents >> Edge(color="gray60", style="dashed") >> n_aws_sns_petEvents
    n_aws_lambda_api >> Edge(label="uses") >> n_aws_dynamodb_petsByOwner
    n_aws_lambda_api >> Edge(label="uses") >> n_aws_sns_petEvents
    n_aws_lambda_worker >> Edge(label="uses") >> n_aws_dynamodb_petsByOwner
    n_aws_lambda_worker >> Edge(label="uses") >> n_aws_s3_petAudit
    n_aws_lambda_worker >> Edge(label="uses") >> n_aws_sns_petEvents
