// Generated by cloudcc for application "petstore-multi". Do not edit: recompiling overwrites
// this file. To change what is generated, edit cloudcc.yaml in your source tree.
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const petApiApi = new aws.apigatewayv2.Api("pet-api", {
    name: "petstore-multi-pet-api",
    protocolType: "HTTP",
});

const apiLogs = new aws.cloudwatch.LogGroup("api", {
    name: "/aws/lambda/petstore-multi-api",
    retentionInDays: 14,
});

const workerLogs = new aws.cloudwatch.LogGroup("worker", {
    name: "/aws/lambda/petstore-multi-worker",
    retentionInDays: 14,
});

const petsByOwnerTable = new aws.dynamodb.Table("petsByOwner", {
    attributes: [
        {
            name: "id",
            type: "S",
        },
    ],
    billingMode: "PAY_PER_REQUEST",
    hashKey: "id",
    name: "petstore-multi-petsByOwner",
});

const apiRole = new aws.iam.Role("api", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "petstore-multi-api-role",
});

const workerRole = new aws.iam.Role("worker", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "petstore-multi-worker-role",
});

const petAuditBucket = new aws.s3.BucketV2("petAudit", {
    bucket: "petstore-multi-petaudit",
    forceDestroy: true,
});

const workerPolicy = new aws.iam.RolePolicy("worker", {
    name: "petstore-multi-worker-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
            ],
            Effect: "Allow",
            Resource: [
                petAuditBucket.arn,
                pulumi.interpolate`${petAuditBucket.arn}/*`,
            ],
        },
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                petsByOwnerTable.arn,
                pulumi.interpolate`${petsByOwnerTable.arn}/index/*`,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: workerRole.id,
});

const petstoreSiteBucket = new aws.s3.BucketV2("petstore-site", {
    bucket: "petstore-multi-petstore-site",
    forceDestroy: true,
});

const petstoreSiteIndexHtmlObject = new aws.s3.BucketObject("petstore-site/index.html", {
    bucket: petstoreSiteBucket.id,
    contentType: "text/html; charset=utf-8",
    key: "index.html",
    source: new pulumi.asset.FileAsset("static/petstore-site/index.html"),
});

const petstoreSiteStyleCssObject = new aws.s3.BucketObject("petstore-site/style.css", {
    bucket: petstoreSiteBucket.id,
    contentType: "text/css; charset=utf-8",
    key: "style.css",
    source: new pulumi.asset.FileAsset("static/petstore-site/style.css"),
});

const petstoreSiteWebsite = new aws.s3.BucketWebsiteConfigurationV2("petstore-site", {
    bucket: petstoreSiteBucket.id,
    indexDocument: {
        suffix: "index.html",
    },
});

const petEventsTopic = new aws.sns.Topic("petEvents", {
    name: "petstore-multi-petEvents",
});

const apiPolicy = new aws.iam.RolePolicy("api", {
    name: "petstore-multi-api-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                petsByOwnerTable.arn,
                pulumi.interpolate`${petsByOwnerTable.arn}/index/*`,
            ],
        },
        {
            Action: [
                "sns:Publish",
            ],
            Effect: "Allow",
            Resource: [
                petEventsTopic.arn,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: apiRole.id,
});

const apiEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_CONFIG_LOG_LEVEL: "info",
    CLOUDCC_KV_PETSBYOWNER_TABLE: pulumi.interpolate`${petsByOwnerTable.name}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_TOPIC_PETEVENTS_ARN: pulumi.interpolate`${petEventsTopic.arn}`,
    CLOUDCC_UNIT: `api`,
    LOG_LEVEL: "info",
};

const apiFn = new aws.lambda.Function("api", {
    code: new pulumi.asset.FileArchive("build/api.zip"),
    environment: { variables: apiEnv },
    handler: "cloudcc_lambda_entry.handler",
    memorySize: 512,
    name: "petstore-multi-api",
    role: apiRole.arn,
    runtime: "python3.12",
    timeout: 30,
});

const petApiIntegration = new aws.apigatewayv2.Integration("pet-api", {
    apiId: petApiApi.id,
    integrationMethod: "POST",
    integrationType: "AWS_PROXY",
    integrationUri: apiFn.arn,
    payloadFormatVersion: "2.0",
});

const petApiRoute = new aws.apigatewayv2.Route("pet-api", {
    apiId: petApiApi.id,
    routeKey: "$default",
    target: pulumi.interpolate`integrations/${petApiIntegration.id}`,
});

const petApiStage = new aws.apigatewayv2.Stage("pet-api", {
    apiId: petApiApi.id,
    autoDeploy: true,
    name: "$default",
});

const petApiPermission = new aws.lambda.Permission("pet-api", {
    action: "lambda:InvokeFunction",
    function: apiFn.name,
    principal: "apigateway.amazonaws.com",
    sourceArn: pulumi.interpolate`${petApiApi.executionArn}/*/*`,
    statementId: "petstore-multi-pet-api-invoke",
});

const workerEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_FS_PETAUDIT_BUCKET: pulumi.interpolate`${petAuditBucket.bucket}`,
    CLOUDCC_KV_PETSBYOWNER_TABLE: pulumi.interpolate`${petsByOwnerTable.name}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_TOPIC_PETEVENTS_ARN: pulumi.interpolate`${petEventsTopic.arn}`,
    CLOUDCC_UNIT: `worker`,
};

const workerFn = new aws.lambda.Function("worker", {
    code: new pulumi.asset.FileArchive("build/worker.zip"),
    environment: { variables: workerEnv },
    handler: "cloudcc_lambda_entry.handler",
    memorySize: 512,
    name: "petstore-multi-worker",
    role: workerRole.arn,
    runtime: "python3.12",
    timeout: 30,
});

const workerPetEventsSnsPermission = new aws.lambda.Permission("worker-petEvents-sns", {
    action: "lambda:InvokeFunction",
    function: workerFn.name,
    principal: "sns.amazonaws.com",
    sourceArn: petEventsTopic.arn,
    statementId: "petstore-multi-worker-petEvents-sns",
});

const workerPetEventsSubscription = new aws.sns.TopicSubscription("worker-petEvents", {
    endpoint: workerFn.arn,
    protocol: "lambda",
    topic: petEventsTopic.arn,
});

// Stack outputs. Every environment binding is exported under the exact
// name the runtime shims read, so a compiled unit can be run locally with:
//   eval "$(pulumi output --json | jq -r 'to_entries[]|"export \(.key)=\(.value)"')"
export const CLOUDCC_FS_PETAUDIT_BUCKET = pulumi.interpolate`${petAuditBucket.bucket}`;
export const CLOUDCC_GATEWAY_PET_API_URL = pulumi.interpolate`${petApiApi.apiEndpoint}`;
export const CLOUDCC_KV_PETSBYOWNER_TABLE = pulumi.interpolate`${petsByOwnerTable.name}`;
export const CLOUDCC_STATIC_PETSTORE_SITE_BUCKET = pulumi.interpolate`${petstoreSiteBucket.bucket}`;
export const CLOUDCC_STATIC_PETSTORE_SITE_URL = pulumi.interpolate`${petstoreSiteWebsite.websiteEndpoint}`;
export const CLOUDCC_TOPIC_PETEVENTS_ARN = pulumi.interpolate`${petEventsTopic.arn}`;
export const petApiUrl = petApiApi.apiEndpoint;
export const petstoreSiteUrl = petstoreSiteWebsite.websiteEndpoint;
