// Generated by cloudcc for application "petstore-multi". Do not edit: recompiling overwrites
// this file. To change what is generated, edit cloudcc.yaml in your source tree.
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const petApiApi = new aws.apigatewayv2.Api("pet-api", {
    name: "petstore-multi-pet-api",
    protocolType: "HTTP",
});

const networkZones = aws.getAvailabilityZonesOutput({
    state: "available",
});

const petstoreSiteOai = new aws.cloudfront.OriginAccessIdentity("petstore-site", {
    comment: "cloudcc petstore-multi static unit petstore-site",
});

const apiLogs = new aws.cloudwatch.LogGroup("api", {
    name: "/aws/lambda/petstore-multi-api",
    retentionInDays: 14,
});

const workerLogs = new aws.cloudwatch.LogGroup("worker", {
    name: "/aws/lambda/petstore-multi-worker",
    retentionInDays: 14,
});

const petsByOwnerTable = new aws.dynamodb.Table("petsByOwner", {
    attributes: [
        {
            name: "id",
            type: "S",
        },
    ],
    billingMode: "PAY_PER_REQUEST",
    hashKey: "id",
    name: "petstore-multi-petsByOwner",
});

const apiRole = new aws.iam.Role("api", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "petstore-multi-api-role",
});

const workerRole = new aws.iam.Role("worker", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "petstore-multi-worker-role",
});

const petAuditBucket = new aws.s3.BucketV2("petAudit", {
    bucket: "petstore-multi-petaudit",
    forceDestroy: true,
});

const petstoreSiteBucket = new aws.s3.BucketV2("petstore-site", {
    bucket: "petstore-multi-petstore-site",
    forceDestroy: true,
});

const petstoreSiteBucketPolicy = new aws.s3.BucketPolicy("petstore-site", {
    bucket: petstoreSiteBucket.id,
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "s3:GetObject",
            ],
            Effect: "Allow",
            Principal: {
                AWS: petstoreSiteOai.iamArn,
            },
            Resource: [
                pulumi.interpolate`${petstoreSiteBucket.arn}/*`,
            ],
        },
    ],
    Version: "2012-10-17",
}),
});

const petstoreSiteCdn = new aws.cloudfront.Distribution("petstore-site", {
    comment: "cloudcc petstore-multi static unit petstore-site",
    defaultCacheBehavior: {
        allowedMethods: [
            "GET",
            "HEAD",
        ],
        cachedMethods: [
            "GET",
            "HEAD",
        ],
        defaultTtl: 3600,
        forwardedValues: {
            cookies: {
                forward: "none",
            },
            queryString: false,
        },
        maxTtl: 86400,
        minTtl: 0,
        targetOriginId: "s3-petstoreSite",
        viewerProtocolPolicy: "redirect-to-https",
    },
    defaultRootObject: "index.html",
    enabled: true,
    origins: [
        {
            domainName: petstoreSiteBucket.bucketRegionalDomainName,
            originId: "s3-petstoreSite",
            s3OriginConfig: {
                originAccessIdentity: petstoreSiteOai.cloudfrontAccessIdentityPath,
            },
        },
    ],
    priceClass: "PriceClass_100",
    restrictions: {
        geoRestriction: {
            restrictionType: "none",
        },
    },
    viewerCertificate: {
        cloudfrontDefaultCertificate: true,
    },
});

const petstoreSiteIndexHtmlObject = new aws.s3.BucketObject("petstore-site/index.html", {
    bucket: petstoreSiteBucket.id,
    contentType: "text/html; charset=utf-8",
    key: "index.html",
    source: new pulumi.asset.FileAsset("static/petstore-site/index.html"),
});

const petstoreSiteStyleCssObject = new aws.s3.BucketObject("petstore-site/style.css", {
    bucket: petstoreSiteBucket.id,
    contentType: "text/css; charset=utf-8",
    key: "style.css",
    source: new pulumi.asset.FileAsset("static/petstore-site/style.css"),
});

const auditKeySecret = new aws.secretsmanager.Secret("auditKey", {
    name: "petstore-multi-auditKey",
    recoveryWindowInDays: 0,
});

const petEventsQueue = new aws.sqs.Queue("petEvents", {
    name: "petstore-multi-petEvents",
    visibilityTimeoutSeconds: 120,
});

const networkVpc = new aws.ec2.Vpc("network", {
    cidrBlock: "10.0.0.0/16",
    enableDnsHostnames: true,
    enableDnsSupport: true,
    tags: {
        Name: "petstore-multi-network",
    },
});

const networkGateway = new aws.ec2.InternetGateway("network", {
    vpcId: networkVpc.id,
});

const networkRoutes = new aws.ec2.RouteTable("network", {
    routes: [
        {
            cidrBlock: "0.0.0.0/0",
            gatewayId: networkGateway.id,
        },
    ],
    vpcId: networkVpc.id,
});

const networkSecurityGroup = new aws.ec2.SecurityGroup("network", {
    description: "Managed by cloudcc: traffic between compiled units and their datastores",
    egress: [
        {
            cidrBlocks: [
                "0.0.0.0/0",
            ],
            fromPort: 0,
            protocol: "-1",
            toPort: 0,
        },
    ],
    ingress: [
        {
            cidrBlocks: [
                "0.0.0.0/0",
            ],
            description: "inbound from the load balancer and within the VPC",
            fromPort: 0,
            protocol: "-1",
            toPort: 0,
        },
    ],
    vpcId: networkVpc.id,
});

const network0Subnet = new aws.ec2.Subnet("network-0", {
    availabilityZone: networkZones.names.apply(n => n[0]),
    cidrBlock: "10.0.0.0/24",
    mapPublicIpOnLaunch: true,
    tags: {
        Name: "petstore-multi-network-0",
    },
    vpcId: networkVpc.id,
});

const network0RouteAssoc = new aws.ec2.RouteTableAssociation("network-0", {
    routeTableId: networkRoutes.id,
    subnetId: network0Subnet.id,
});

const network1Subnet = new aws.ec2.Subnet("network-1", {
    availabilityZone: networkZones.names.apply(n => n[1]),
    cidrBlock: "10.0.1.0/24",
    mapPublicIpOnLaunch: true,
    tags: {
        Name: "petstore-multi-network-1",
    },
    vpcId: networkVpc.id,
});

const elasticacheSubnetGroup = new aws.elasticache.SubnetGroup("elasticache", {
    name: "petstore-multi-elasticache",
    subnetIds: [
        network0Subnet.id,
        network1Subnet.id,
    ],
});

const petCacheCache = new aws.elasticache.Cluster("petCache", {
    clusterId: "petstore-multi-petcache",
    engine: "redis",
    nodeType: "cache.t4g.micro",
    numCacheNodes: 1,
    port: 6379,
    securityGroupIds: [
        networkSecurityGroup.id,
    ],
    subnetGroupName: elasticacheSubnetGroup.name,
});

const rdsSubnetGroup = new aws.rds.SubnetGroup("rds", {
    name: "petstore-multi-rds",
    subnetIds: [
        network0Subnet.id,
        network1Subnet.id,
    ],
});

const auditdbDb = new aws.rds.Instance("auditdb", {
    allocatedStorage: 20,
    dbName: "auditdb",
    dbSubnetGroupName: rdsSubnetGroup.name,
    engine: "postgres",
    identifier: "petstore-multi-auditdb",
    instanceClass: "db.t4g.micro",
    manageMasterUserPassword: true,
    publiclyAccessible: false,
    skipFinalSnapshot: true,
    username: "ccadmin",
    vpcSecurityGroupIds: [
        networkSecurityGroup.id,
    ],
});

const workerPolicy = new aws.iam.RolePolicy("worker", {
    name: "petstore-multi-worker-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
            ],
            Effect: "Allow",
            Resource: [
                petAuditBucket.arn,
                pulumi.interpolate`${petAuditBucket.arn}/*`,
            ],
        },
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                petsByOwnerTable.arn,
                pulumi.interpolate`${petsByOwnerTable.arn}/index/*`,
            ],
        },
        {
            Action: [
                "secretsmanager:GetSecretValue",
            ],
            Effect: "Allow",
            Resource: [
                auditdbDb.masterUserSecrets.apply(s => s?.[0]?.secretArn ?? ""),
            ],
        },
        {
            Action: [
                "secretsmanager:GetSecretValue",
                "secretsmanager:PutSecretValue",
            ],
            Effect: "Allow",
            Resource: [
                auditKeySecret.arn,
            ],
        },
        {
            Action: [
                "sqs:ReceiveMessage",
                "sqs:DeleteMessage",
                "sqs:GetQueueAttributes",
            ],
            Effect: "Allow",
            Resource: [
                petEventsQueue.arn,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: workerRole.id,
});

const workerEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_FS_PETAUDIT_BUCKET: pulumi.interpolate`${petAuditBucket.bucket}`,
    CLOUDCC_KV_PETSBYOWNER_TABLE: pulumi.interpolate`${petsByOwnerTable.name}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_ORM_AUDITDB_SECRET_ARN: pulumi.interpolate`${auditdbDb.masterUserSecrets.apply(s => s?.[0]?.secretArn ?? "")}`,
    CLOUDCC_ORM_AUDITDB_URL: pulumi.interpolate`postgresql://ccadmin@${auditdbDb.address}:${auditdbDb.port}/auditdb`,
    CLOUDCC_SECRET_AUDITKEY_ARN: pulumi.interpolate`${auditKeySecret.arn}`,
    CLOUDCC_TOPIC_PETEVENTS_ARN: pulumi.interpolate`${petEventsQueue.arn}`,
    CLOUDCC_TOPIC_PETEVENTS_BACKING: "sqs",
    CLOUDCC_TOPIC_PETEVENTS_URL: pulumi.interpolate`${petEventsQueue.url}`,
    CLOUDCC_UNIT: `worker`,
};

const workerFn = new aws.lambda.Function("worker", {
    architectures: [
        "arm64",
    ],
    code: new pulumi.asset.FileArchive("build/worker.zip"),
    environment: { variables: workerEnv },
    handler: "cloudcc_lambda_entry.handler",
    memorySize: 512,
    name: "petstore-multi-worker",
    role: workerRole.arn,
    runtime: "python3.12",
    timeout: 120,
});

const workerPetEventsEventSource = new aws.lambda.EventSourceMapping("worker-petEvents", {
    batchSize: 1,
    eventSourceArn: petEventsQueue.arn,
    functionName: workerFn.arn,
}, {
    dependsOn: [
        workerPolicy,
    ],
});

const petsdbDb = new aws.rds.Instance("petsdb", {
    allocatedStorage: 20,
    dbName: "petsdb",
    dbSubnetGroupName: rdsSubnetGroup.name,
    engine: "postgres",
    identifier: "petstore-multi-petsdb",
    instanceClass: "db.t4g.micro",
    manageMasterUserPassword: true,
    publiclyAccessible: false,
    skipFinalSnapshot: true,
    username: "ccadmin",
    vpcSecurityGroupIds: [
        networkSecurityGroup.id,
    ],
});

const apiPolicy = new aws.iam.RolePolicy("api", {
    name: "petstore-multi-api-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                petsByOwnerTable.arn,
                pulumi.interpolate`${petsByOwnerTable.arn}/index/*`,
            ],
        },
        {
            Action: [
                "secretsmanager:GetSecretValue",
            ],
            Effect: "Allow",
            Resource: [
                petsdbDb.masterUserSecrets.apply(s => s?.[0]?.secretArn ?? ""),
            ],
        },
        {
            Action: [
                "sqs:SendMessage",
            ],
            Effect: "Allow",
            Resource: [
                petEventsQueue.arn,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: apiRole.id,
});

const apiEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_CONFIG_LOG_LEVEL: "info",
    CLOUDCC_KV_PETSBYOWNER_TABLE: pulumi.interpolate`${petsByOwnerTable.name}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_ORM_PETSDB_SECRET_ARN: pulumi.interpolate`${petsdbDb.masterUserSecrets.apply(s => s?.[0]?.secretArn ?? "")}`,
    CLOUDCC_ORM_PETSDB_URL: pulumi.interpolate`postgresql://ccadmin@${petsdbDb.address}:${petsdbDb.port}/petsdb`,
    CLOUDCC_REDIS_PETCACHE_ENDPOINT: pulumi.interpolate`${petCacheCache.cacheNodes.apply(n => n?.[0]?.address ?? "")}`,
    CLOUDCC_REDIS_PETCACHE_PORT: "6379",
    CLOUDCC_REDIS_PETCACHE_TLS: "false",
    CLOUDCC_TOPIC_PETEVENTS_ARN: pulumi.interpolate`${petEventsQueue.arn}`,
    CLOUDCC_TOPIC_PETEVENTS_BACKING: "sqs",
    CLOUDCC_TOPIC_PETEVENTS_URL: pulumi.interpolate`${petEventsQueue.url}`,
    CLOUDCC_UNIT: `api`,
    LOG_LEVEL: "info",
};

const apiFn = new aws.lambda.Function("api", {
    architectures: [
        "arm64",
    ],
    code: new pulumi.asset.FileArchive("build/api.zip"),
    environment: { variables: apiEnv },
    handler: "cloudcc_lambda_entry.handler",
    memorySize: 1024,
    name: "petstore-multi-api",
    role: apiRole.arn,
    runtime: "python3.12",
    timeout: 30,
});

const petApiIntegration = new aws.apigatewayv2.Integration("pet-api", {
    apiId: petApiApi.id,
    integrationMethod: "POST",
    integrationType: "AWS_PROXY",
    integrationUri: apiFn.arn,
    payloadFormatVersion: "2.0",
});

const petApiRoute = new aws.apigatewayv2.Route("pet-api", {
    apiId: petApiApi.id,
    routeKey: "$default",
    target: pulumi.interpolate`integrations/${petApiIntegration.id}`,
});

const petApiStage = new aws.apigatewayv2.Stage("pet-api", {
    apiId: petApiApi.id,
    autoDeploy: true,
    name: "$default",
});

const petApiPermission = new aws.lambda.Permission("pet-api", {
    action: "lambda:InvokeFunction",
    function: apiFn.name,
    principal: "apigateway.amazonaws.com",
    sourceArn: pulumi.interpolate`${petApiApi.executionArn}/*/*`,
    statementId: "petstore-multi-pet-api-invoke",
});

const network1RouteAssoc = new aws.ec2.RouteTableAssociation("network-1", {
    routeTableId: networkRoutes.id,
    subnetId: network1Subnet.id,
});

// Stack outputs. Every environment binding is exported under the exact
// name the runtime shims read, so a compiled unit can be run locally with:
//   eval "$(pulumi output --json | jq -r 'to_entries[]|"export \(.key)=\(.value)"')"
export const CLOUDCC_FS_PETAUDIT_BUCKET = pulumi.interpolate`${petAuditBucket.bucket}`;
export const CLOUDCC_GATEWAY_PET_API_URL = pulumi.interpolate`${petApiApi.apiEndpoint}`;
export const CLOUDCC_KV_PETSBYOWNER_TABLE = pulumi.interpolate`${petsByOwnerTable.name}`;
export const CLOUDCC_ORM_AUDITDB_SECRET_ARN = pulumi.interpolate`${auditdbDb.masterUserSecrets.apply(s => s?.[0]?.secretArn ?? "")}`;
export const CLOUDCC_ORM_AUDITDB_URL = pulumi.interpolate`postgresql://ccadmin@${auditdbDb.address}:${auditdbDb.port}/auditdb`;
export const CLOUDCC_ORM_PETSDB_SECRET_ARN = pulumi.interpolate`${petsdbDb.masterUserSecrets.apply(s => s?.[0]?.secretArn ?? "")}`;
export const CLOUDCC_ORM_PETSDB_URL = pulumi.interpolate`postgresql://ccadmin@${petsdbDb.address}:${petsdbDb.port}/petsdb`;
export const CLOUDCC_REDIS_PETCACHE_ENDPOINT = pulumi.interpolate`${petCacheCache.cacheNodes.apply(n => n?.[0]?.address ?? "")}`;
export const CLOUDCC_REDIS_PETCACHE_PORT = "6379";
export const CLOUDCC_REDIS_PETCACHE_TLS = "false";
export const CLOUDCC_SECRET_AUDITKEY_ARN = pulumi.interpolate`${auditKeySecret.arn}`;
export const CLOUDCC_STATIC_PETSTORE_SITE_BUCKET = pulumi.interpolate`${petstoreSiteBucket.bucket}`;
export const CLOUDCC_STATIC_PETSTORE_SITE_URL = pulumi.interpolate`${petstoreSiteCdn.domainName}`;
export const CLOUDCC_TOPIC_PETEVENTS_ARN = pulumi.interpolate`${petEventsQueue.arn}`;
export const CLOUDCC_TOPIC_PETEVENTS_BACKING = "sqs";
export const CLOUDCC_TOPIC_PETEVENTS_URL = pulumi.interpolate`${petEventsQueue.url}`;
export const CLOUDCC_UNIT_API_FUNCTION = pulumi.interpolate`${apiFn.name}`;
export const CLOUDCC_UNIT_WORKER_FUNCTION = pulumi.interpolate`${workerFn.name}`;
export const petApiUrl = petApiApi.apiEndpoint;
export const petEventsUrl = petEventsQueue.url;
export const petstoreSiteUrl = petstoreSiteCdn.domainName;
