"""Architecture of mixed, generated by cloudcc.

Diagram as code, using https://pypi.org/project/diagrams -- one icon per
capability, showing the service each one resolved to and how the program said
they are connected.

The supporting cast is deliberately absent: roles, policies, log groups and an
HTTP API's internal wiring all exist, and all of them are in architecture.mmd
and architecture.dot. This file answers "what is this system", not "what will
exist in the account".

    pip install diagrams   # and graphviz
    python architecture.py

Recompiling overwrites this file. Copy it before editing.
"""

from diagrams import Diagram, Edge
from diagrams.aws.compute import Lambda
from diagrams.aws.database import Dynamodb, ElastiCache, RDS
from diagrams.aws.network import APIGateway
from diagrams.aws.storage import S3

with Diagram(
    "mixed",
    filename="mixed-architecture",
    outformat="png",
    show=False,
    direction="LR",
):
    n_execution_unit_api = Lambda("api\nLambda")
    n_execution_unit_worker = Lambda("worker\nLambda")
    n_expose_pet_api = APIGateway("pet-api\nAPI Gateway")
    n_persist_fs_petPhotos = S3("petPhotos\nS3")
    n_persist_kv_petsByOwner = Dynamodb("petsByOwner\nDynamoDB")
    n_persist_orm_shopdb = RDS("shopdb\nRDS")
    n_persist_redis_petCache = ElastiCache("petCache\nElastiCache")

    n_expose_pet_api >> n_execution_unit_api
    n_execution_unit_api >> n_persist_fs_petPhotos
    n_execution_unit_api >> n_persist_kv_petsByOwner
    n_execution_unit_api >> n_persist_orm_shopdb
    n_execution_unit_api >> n_persist_redis_petCache
    n_execution_unit_worker >> n_persist_fs_petPhotos
    n_execution_unit_worker >> n_persist_kv_petsByOwner
    n_execution_unit_worker >> n_persist_orm_shopdb
