// Generated by cloudcc for application "mixed". Do not edit: recompiling overwrites
// this file. To change what is generated, edit cloudcc.yaml in your source tree.
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const petApiApi = new aws.apigatewayv2.Api("pet-api", {
    name: "mixed-pet-api",
    protocolType: "HTTP",
});

const networkZones = aws.getAvailabilityZonesOutput({
    state: "available",
});

const apiLogs = new aws.cloudwatch.LogGroup("api", {
    name: "/aws/lambda/mixed-api",
    retentionInDays: 14,
});

const workerLogs = new aws.cloudwatch.LogGroup("worker", {
    name: "/aws/lambda/mixed-worker",
    retentionInDays: 14,
});

const petsByOwnerTable = new aws.dynamodb.Table("petsByOwner", {
    attributes: [
        {
            name: "id",
            type: "S",
        },
    ],
    billingMode: "PAY_PER_REQUEST",
    hashKey: "id",
    name: "mixed-petsByOwner",
});

const apiRole = new aws.iam.Role("api", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "mixed-api-role",
});

const workerRole = new aws.iam.Role("worker", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "mixed-worker-role",
});

const petPhotosBucket = new aws.s3.BucketV2("petPhotos", {
    bucket: "mixed-petphotos",
    forceDestroy: true,
});

const networkVpc = new aws.ec2.Vpc("network", {
    cidrBlock: "10.0.0.0/16",
    enableDnsHostnames: true,
    enableDnsSupport: true,
    tags: {
        Name: "mixed-network",
    },
});

const networkGateway = new aws.ec2.InternetGateway("network", {
    vpcId: networkVpc.id,
});

const networkRoutes = new aws.ec2.RouteTable("network", {
    routes: [
        {
            cidrBlock: "0.0.0.0/0",
            gatewayId: networkGateway.id,
        },
    ],
    vpcId: networkVpc.id,
});

const networkSecurityGroup = new aws.ec2.SecurityGroup("network", {
    description: "Managed by cloudcc: traffic between compiled units and their datastores",
    egress: [
        {
            cidrBlocks: [
                "0.0.0.0/0",
            ],
            fromPort: 0,
            protocol: "-1",
            toPort: 0,
        },
    ],
    ingress: [
        {
            cidrBlocks: [
                "0.0.0.0/0",
            ],
            description: "inbound from the load balancer and within the VPC",
            fromPort: 0,
            protocol: "-1",
            toPort: 0,
        },
    ],
    vpcId: networkVpc.id,
});

const network0Subnet = new aws.ec2.Subnet("network-0", {
    availabilityZone: networkZones.names.apply(n => n[0]),
    cidrBlock: "10.0.0.0/24",
    mapPublicIpOnLaunch: true,
    tags: {
        Name: "mixed-network-0",
    },
    vpcId: networkVpc.id,
});

const network0RouteAssoc = new aws.ec2.RouteTableAssociation("network-0", {
    routeTableId: networkRoutes.id,
    subnetId: network0Subnet.id,
});

const network1Subnet = new aws.ec2.Subnet("network-1", {
    availabilityZone: networkZones.names.apply(n => n[1]),
    cidrBlock: "10.0.1.0/24",
    mapPublicIpOnLaunch: true,
    tags: {
        Name: "mixed-network-1",
    },
    vpcId: networkVpc.id,
});

const elasticacheSubnetGroup = new aws.elasticache.SubnetGroup("elasticache", {
    name: "mixed-elasticache",
    subnetIds: [
        network0Subnet.id,
        network1Subnet.id,
    ],
});

const petCacheCache = new aws.elasticache.Cluster("petCache", {
    clusterId: "mixed-petcache",
    engine: "redis",
    nodeType: "cache.t4g.micro",
    numCacheNodes: 1,
    port: 6379,
    securityGroupIds: [
        networkSecurityGroup.id,
    ],
    subnetGroupName: elasticacheSubnetGroup.name,
});

const rdsSubnetGroup = new aws.rds.SubnetGroup("rds", {
    name: "mixed-rds",
    subnetIds: [
        network0Subnet.id,
        network1Subnet.id,
    ],
});

const shopdbDb = new aws.rds.Instance("shopdb", {
    allocatedStorage: 20,
    dbName: "shopdb",
    dbSubnetGroupName: rdsSubnetGroup.name,
    engine: "postgres",
    identifier: "mixed-shopdb",
    instanceClass: "db.t4g.micro",
    manageMasterUserPassword: true,
    publiclyAccessible: false,
    skipFinalSnapshot: true,
    username: "ccadmin",
    vpcSecurityGroupIds: [
        networkSecurityGroup.id,
    ],
});

const apiPolicy = new aws.iam.RolePolicy("api", {
    name: "mixed-api-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
            ],
            Effect: "Allow",
            Resource: [
                petPhotosBucket.arn,
                pulumi.interpolate`${petPhotosBucket.arn}/*`,
            ],
        },
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                petsByOwnerTable.arn,
                pulumi.interpolate`${petsByOwnerTable.arn}/index/*`,
            ],
        },
        {
            Action: [
                "secretsmanager:GetSecretValue",
            ],
            Effect: "Allow",
            Resource: [
                shopdbDb.masterUserSecrets.apply(s => s?.[0]?.secretArn ?? ""),
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: apiRole.id,
});

const workerPolicy = new aws.iam.RolePolicy("worker", {
    name: "mixed-worker-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
            ],
            Effect: "Allow",
            Resource: [
                petPhotosBucket.arn,
                pulumi.interpolate`${petPhotosBucket.arn}/*`,
            ],
        },
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                petsByOwnerTable.arn,
                pulumi.interpolate`${petsByOwnerTable.arn}/index/*`,
            ],
        },
        {
            Action: [
                "secretsmanager:GetSecretValue",
            ],
            Effect: "Allow",
            Resource: [
                shopdbDb.masterUserSecrets.apply(s => s?.[0]?.secretArn ?? ""),
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: workerRole.id,
});

const apiEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_FS_PETPHOTOS_BUCKET: pulumi.interpolate`${petPhotosBucket.bucket}`,
    CLOUDCC_KV_PETSBYOWNER_TABLE: pulumi.interpolate`${petsByOwnerTable.name}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_ORM_SHOPDB_SECRET_ARN: pulumi.interpolate`${shopdbDb.masterUserSecrets.apply(s => s?.[0]?.secretArn ?? "")}`,
    CLOUDCC_ORM_SHOPDB_URL: pulumi.interpolate`postgresql://ccadmin@${shopdbDb.address}:${shopdbDb.port}/shopdb`,
    CLOUDCC_REDIS_PETCACHE_ENDPOINT: pulumi.interpolate`${petCacheCache.cacheNodes.apply(n => n?.[0]?.address ?? "")}`,
    CLOUDCC_REDIS_PETCACHE_PORT: "6379",
    CLOUDCC_REDIS_PETCACHE_TLS: "false",
    CLOUDCC_UNIT: `api`,
};

const apiFn = new aws.lambda.Function("api", {
    code: new pulumi.asset.FileArchive("build/api.zip"),
    environment: { variables: apiEnv },
    handler: "index.handler",
    memorySize: 512,
    name: "mixed-api",
    role: apiRole.arn,
    runtime: "nodejs22.x",
    timeout: 30,
});

const petApiIntegration = new aws.apigatewayv2.Integration("pet-api", {
    apiId: petApiApi.id,
    integrationMethod: "POST",
    integrationType: "AWS_PROXY",
    integrationUri: apiFn.arn,
    payloadFormatVersion: "2.0",
});

const petApiRoute = new aws.apigatewayv2.Route("pet-api", {
    apiId: petApiApi.id,
    routeKey: "$default",
    target: pulumi.interpolate`integrations/${petApiIntegration.id}`,
});

const petApiStage = new aws.apigatewayv2.Stage("pet-api", {
    apiId: petApiApi.id,
    autoDeploy: true,
    name: "$default",
});

const petApiPermission = new aws.lambda.Permission("pet-api", {
    action: "lambda:InvokeFunction",
    function: apiFn.name,
    principal: "apigateway.amazonaws.com",
    sourceArn: pulumi.interpolate`${petApiApi.executionArn}/*/*`,
    statementId: "mixed-pet-api-invoke",
});

const workerEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_FS_PETPHOTOS_BUCKET: pulumi.interpolate`${petPhotosBucket.bucket}`,
    CLOUDCC_KV_PETSBYOWNER_TABLE: pulumi.interpolate`${petsByOwnerTable.name}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_ORM_SHOPDB_SECRET_ARN: pulumi.interpolate`${shopdbDb.masterUserSecrets.apply(s => s?.[0]?.secretArn ?? "")}`,
    CLOUDCC_ORM_SHOPDB_URL: pulumi.interpolate`postgresql://ccadmin@${shopdbDb.address}:${shopdbDb.port}/shopdb`,
    CLOUDCC_UNIT: `worker`,
};

const workerFn = new aws.lambda.Function("worker", {
    code: new pulumi.asset.FileArchive("build/worker.zip"),
    environment: { variables: workerEnv },
    handler: "cloudcc_lambda_entry.handler",
    memorySize: 512,
    name: "mixed-worker",
    role: workerRole.arn,
    runtime: "python3.12",
    timeout: 30,
});

const network1RouteAssoc = new aws.ec2.RouteTableAssociation("network-1", {
    routeTableId: networkRoutes.id,
    subnetId: network1Subnet.id,
});

// Stack outputs. Every environment binding is exported under the exact
// name the runtime shims read, so a compiled unit can be run locally with:
//   eval "$(pulumi output --json | jq -r 'to_entries[]|"export \(.key)=\(.value)"')"
export const CLOUDCC_FS_PETPHOTOS_BUCKET = pulumi.interpolate`${petPhotosBucket.bucket}`;
export const CLOUDCC_GATEWAY_PET_API_URL = pulumi.interpolate`${petApiApi.apiEndpoint}`;
export const CLOUDCC_KV_PETSBYOWNER_TABLE = pulumi.interpolate`${petsByOwnerTable.name}`;
export const CLOUDCC_ORM_SHOPDB_SECRET_ARN = pulumi.interpolate`${shopdbDb.masterUserSecrets.apply(s => s?.[0]?.secretArn ?? "")}`;
export const CLOUDCC_ORM_SHOPDB_URL = pulumi.interpolate`postgresql://ccadmin@${shopdbDb.address}:${shopdbDb.port}/shopdb`;
export const CLOUDCC_REDIS_PETCACHE_ENDPOINT = pulumi.interpolate`${petCacheCache.cacheNodes.apply(n => n?.[0]?.address ?? "")}`;
export const CLOUDCC_REDIS_PETCACHE_PORT = "6379";
export const CLOUDCC_REDIS_PETCACHE_TLS = "false";
export const CLOUDCC_UNIT_API_FUNCTION = pulumi.interpolate`${apiFn.name}`;
export const CLOUDCC_UNIT_WORKER_FUNCTION = pulumi.interpolate`${workerFn.name}`;
export const petApiUrl = petApiApi.apiEndpoint;
