// Generated by cloudcc for application "mixed". Do not edit: recompiling overwrites
// this file. To change what is generated, edit cloudcc.yaml in your source tree.
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const petApiApi = new aws.apigatewayv2.Api("pet-api", {
    name: "mixed-pet-api",
    protocolType: "HTTP",
});

const apiLogs = new aws.cloudwatch.LogGroup("api", {
    name: "/aws/lambda/mixed-api",
    retentionInDays: 14,
});

const workerLogs = new aws.cloudwatch.LogGroup("worker", {
    name: "/aws/lambda/mixed-worker",
    retentionInDays: 14,
});

const petsByOwnerTable = new aws.dynamodb.Table("petsByOwner", {
    attributes: [
        {
            name: "id",
            type: "S",
        },
    ],
    billingMode: "PAY_PER_REQUEST",
    hashKey: "id",
    name: "mixed-petsByOwner",
});

const apiRole = new aws.iam.Role("api", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "mixed-api-role",
});

const apiPolicy = new aws.iam.RolePolicy("api", {
    name: "mixed-api-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                petsByOwnerTable.arn,
                pulumi.interpolate`${petsByOwnerTable.arn}/index/*`,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: apiRole.id,
});

const workerRole = new aws.iam.Role("worker", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "mixed-worker-role",
});

const workerPolicy = new aws.iam.RolePolicy("worker", {
    name: "mixed-worker-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                petsByOwnerTable.arn,
                pulumi.interpolate`${petsByOwnerTable.arn}/index/*`,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: workerRole.id,
});

const apiEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_KV_PETSBYOWNER_TABLE: pulumi.interpolate`${petsByOwnerTable.name}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_UNIT: `api`,
};

const apiFn = new aws.lambda.Function("api", {
    code: new pulumi.asset.FileArchive("build/api.zip"),
    environment: { variables: apiEnv },
    handler: "index.handler",
    memorySize: 512,
    name: "mixed-api",
    role: apiRole.arn,
    runtime: "nodejs22.x",
    timeout: 30,
});

const petApiIntegration = new aws.apigatewayv2.Integration("pet-api", {
    apiId: petApiApi.id,
    integrationMethod: "POST",
    integrationType: "AWS_PROXY",
    integrationUri: apiFn.arn,
    payloadFormatVersion: "2.0",
});

const petApiRoute = new aws.apigatewayv2.Route("pet-api", {
    apiId: petApiApi.id,
    routeKey: "$default",
    target: pulumi.interpolate`integrations/${petApiIntegration.id}`,
});

const petApiStage = new aws.apigatewayv2.Stage("pet-api", {
    apiId: petApiApi.id,
    autoDeploy: true,
    name: "$default",
});

const petApiPermission = new aws.lambda.Permission("pet-api", {
    action: "lambda:InvokeFunction",
    function: apiFn.name,
    principal: "apigateway.amazonaws.com",
    sourceArn: pulumi.interpolate`${petApiApi.executionArn}/*/*`,
    statementId: "mixed-pet-api-invoke",
});

const workerEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_KV_PETSBYOWNER_TABLE: pulumi.interpolate`${petsByOwnerTable.name}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_UNIT: `worker`,
};

const workerFn = new aws.lambda.Function("worker", {
    code: new pulumi.asset.FileArchive("build/worker.zip"),
    environment: { variables: workerEnv },
    handler: "cloudcc_lambda_entry.handler",
    memorySize: 512,
    name: "mixed-worker",
    role: workerRole.arn,
    runtime: "python3.12",
    timeout: 30,
});

// Stack outputs. Every environment binding is exported under the exact
// name the runtime shims read, so a compiled unit can be run locally with:
//   eval "$(pulumi output --json | jq -r 'to_entries[]|"export \(.key)=\(.value)"')"
export const CLOUDCC_GATEWAY_PET_API_URL = pulumi.interpolate`${petApiApi.apiEndpoint}`;
export const CLOUDCC_KV_PETSBYOWNER_TABLE = pulumi.interpolate`${petsByOwnerTable.name}`;
export const CLOUDCC_UNIT_API_FUNCTION = pulumi.interpolate`${apiFn.name}`;
export const CLOUDCC_UNIT_WORKER_FUNCTION = pulumi.interpolate`${workerFn.name}`;
export const petApiUrl = petApiApi.apiEndpoint;
