// Generated by cloudcc for application "k8s-web". Do not edit: recompiling overwrites
// this file. To change what is generated, edit cloudcc.yaml in your source tree.
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as k8s from "@pulumi/kubernetes";

const networkZones = aws.getAvailabilityZonesOutput({
    state: "available",
});

const webRepo = new aws.ecr.Repository("web", {
    forceDelete: true,
    name: "k8s-web-web",
});

const kubernetesRole = new aws.iam.Role("kubernetes", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "eks.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy",
    ],
    name: "k8s-web-kubernetes-cluster",
});

const kubernetesRole2 = new aws.iam.Role("kubernetes-2", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "ec2.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
        "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
        "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly",
    ],
    name: "k8s-web-kubernetes-node",
});

const networkVpc = new aws.ec2.Vpc("network", {
    cidrBlock: "10.0.0.0/16",
    enableDnsHostnames: true,
    enableDnsSupport: true,
    tags: {
        Name: "k8s-web-network",
    },
});

const networkGateway = new aws.ec2.InternetGateway("network", {
    vpcId: networkVpc.id,
});

const networkRoutes = new aws.ec2.RouteTable("network", {
    routes: [
        {
            cidrBlock: "0.0.0.0/0",
            gatewayId: networkGateway.id,
        },
    ],
    vpcId: networkVpc.id,
});

const networkSecurityGroup = new aws.ec2.SecurityGroup("network", {
    description: "Managed by cloudcc: traffic between compiled units and their datastores",
    egress: [
        {
            cidrBlocks: [
                "0.0.0.0/0",
            ],
            fromPort: 0,
            protocol: "-1",
            toPort: 0,
        },
    ],
    ingress: [
        {
            cidrBlocks: [
                "0.0.0.0/0",
            ],
            description: "inbound from the load balancer and within the VPC",
            fromPort: 0,
            protocol: "-1",
            toPort: 0,
        },
    ],
    vpcId: networkVpc.id,
});

const network0Subnet = new aws.ec2.Subnet("network-0", {
    availabilityZone: networkZones.names.apply(n => n[0]),
    cidrBlock: "10.0.0.0/24",
    mapPublicIpOnLaunch: true,
    tags: {
        Name: "k8s-web-network-0",
    },
    vpcId: networkVpc.id,
});

const network0RouteAssoc = new aws.ec2.RouteTableAssociation("network-0", {
    routeTableId: networkRoutes.id,
    subnetId: network0Subnet.id,
});

const network1Subnet = new aws.ec2.Subnet("network-1", {
    availabilityZone: networkZones.names.apply(n => n[1]),
    cidrBlock: "10.0.1.0/24",
    mapPublicIpOnLaunch: true,
    tags: {
        Name: "k8s-web-network-1",
    },
    vpcId: networkVpc.id,
});

const kubernetesEks = new aws.eks.Cluster("kubernetes", {
    name: "k8s-web-kubernetes",
    roleArn: kubernetesRole.arn,
    vpcConfig: {
        subnetIds: [
            network0Subnet.id,
            network1Subnet.id,
        ],
    },
});

const kubernetesNodes = new aws.eks.NodeGroup("kubernetes", {
    clusterName: kubernetesEks.name,
    nodeGroupName: "k8s-web-kubernetes-nodes",
    nodeRoleArn: kubernetesRole2.arn,
    scalingConfig: {
        desiredSize: 1,
        maxSize: 2,
        minSize: 1,
    },
    subnetIds: [
        network0Subnet.id,
        network1Subnet.id,
    ],
});

const network1RouteAssoc = new aws.ec2.RouteTableAssociation("network-1", {
    routeTableId: networkRoutes.id,
    subnetId: network1Subnet.id,
});

const kubernetesK8s = new k8s.Provider("kubernetes", {
    kubeconfig: process.env.CLOUDCC_KUBECONFIG ?? pulumi.interpolate`apiVersion: v1
clusters:
- cluster:
    server: ${kubernetesEks.endpoint}
    certificate-authority-data: ${kubernetesEks.certificateAuthority.data}
  name: cloudcc
contexts:
- context:
    cluster: cloudcc
    user: cloudcc
  name: cloudcc
current-context: cloudcc
kind: Config
users:
- name: cloudcc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args: ["eks", "get-token", "--cluster-name", "${kubernetesEks.name}"]
`,
});

const webEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_UNIT: `web`,
};

const webDeployment = new k8s.apps.v1.Deployment("web", {
    metadata: {
        labels: {
            app: "web",
        },
        name: "k8s-web-web",
    },
    spec: {
        replicas: 1,
        selector: {
            matchLabels: {
                app: "web",
            },
        },
        template: {
            metadata: {
                labels: {
                    app: "web",
                },
            },
            spec: {
                containers: [
                    {
                        env: Object.entries(webEnv).map(([name, value]) => ({ name, value: value as pulumi.Input<string> })),
                        image: pulumi.interpolate`${webRepo.repositoryUrl}:latest`,
                        name: "web",
                        ports: [
                            {
                                containerPort: 8080,
                            },
                        ],
                        resources: {
                            limits: {
                                cpu: "250m",
                                memory: "512Mi",
                            },
                            requests: {
                                cpu: "250m",
                                memory: "512Mi",
                            },
                        },
                    },
                ],
            },
        },
    },
}, {
    provider: kubernetesK8s,
});

const webSvc = new k8s.core.v1.Service("web", {
    metadata: {
        labels: {
            app: "web",
        },
        name: "k8s-web-web",
    },
    spec: {
        ports: [
            {
                port: 80,
                protocol: "TCP",
                targetPort: 8080,
            },
        ],
        selector: {
            app: "web",
        },
        type: "LoadBalancer",
    },
}, {
    dependsOn: [
        webDeployment,
    ],
    provider: kubernetesK8s,
});

// Stack outputs. Every environment binding is exported under the exact
// name the runtime shims read, so a compiled unit can be run locally with:
//   eval "$(pulumi output --json | jq -r 'to_entries[]|"export \(.key)=\(.value)"')"
export const CLOUDCC_CLUSTER_KUBERNETES_ENDPOINT = pulumi.interpolate`${kubernetesEks.endpoint}`;
export const CLOUDCC_ECR_WEB_URL = pulumi.interpolate`${webRepo.repositoryUrl}`;
export const kubernetesUrl = kubernetesEks.endpoint;
