"""Architecture of petstore-ts, generated by cloudcc.

Diagram as code, using https://pypi.org/project/diagrams -- one icon per
capability, showing the service each one resolved to and how the program said
they are connected.

The supporting cast is deliberately absent: roles, policies, log groups and an
HTTP API's internal wiring all exist, and all of them are in architecture.mmd
and architecture.dot. This file answers "what is this system", not "what will
exist in the account".

    pip install diagrams   # and graphviz
    python architecture.py

Recompiling overwrites this file. Copy it before editing.
"""

from diagrams import Diagram, Edge
from diagrams.aws.compute import ElasticContainerServiceService, Lambda
from diagrams.aws.database import Dynamodb
from diagrams.aws.network import ElbApplicationLoadBalancer

with Diagram(
    "petstore-ts",
    filename="petstore-ts-architecture",
    outformat="png",
    show=False,
    direction="LR",
):
    n_execution_unit_summary = Lambda("summary\nLambda")
    n_execution_unit_web = ElasticContainerServiceService("web\nFargate")
    n_expose_pet_api = ElbApplicationLoadBalancer("pet-api\nLoad Balancer")
    n_persist_kv_petsByOwner = Dynamodb("petsByOwner\nDynamoDB")

    n_execution_unit_web >> Edge(label="calls", color="darkorange", style="bold") >> n_execution_unit_summary
    n_expose_pet_api >> n_execution_unit_web
    n_execution_unit_web >> n_persist_kv_petsByOwner
