// Generated by cloudcc for application "petstore-ts". Do not edit: recompiling overwrites
// this file. To change what is generated, edit cloudcc.yaml in your source tree.
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const networkZones = aws.getAvailabilityZonesOutput({
    state: "available",
});

const summaryLogs = new aws.cloudwatch.LogGroup("summary", {
    name: "/aws/lambda/petstore-ts-summary",
    retentionInDays: 14,
});

const webLogs = new aws.cloudwatch.LogGroup("web", {
    name: "/ecs/petstore-ts-web",
    retentionInDays: 14,
});

const petsByOwnerTable = new aws.dynamodb.Table("petsByOwner", {
    attributes: [
        {
            name: "id",
            type: "S",
        },
    ],
    billingMode: "PAY_PER_REQUEST",
    hashKey: "id",
    name: "petstore-ts-petsByOwner",
});

const webRepo = new aws.ecr.Repository("web", {
    forceDelete: true,
    name: "petstore-ts-web",
});

const clusterCluster = new aws.ecs.Cluster("cluster", {
    name: "petstore-ts-cluster",
});

const webExecRole = new aws.iam.Role("web-exec", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "ecs-tasks.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy",
    ],
    name: "petstore-ts-web-exec",
});

const webTaskRole = new aws.iam.Role("web-task", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "ecs-tasks.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    name: "petstore-ts-web-task",
});

const summaryRole = new aws.iam.Role("summary", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "petstore-ts-summary-role",
});

const summaryEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_UNIT: `summary`,
};

const summaryFn = new aws.lambda.Function("summary", {
    code: new pulumi.asset.FileArchive("build/summary.zip"),
    environment: { variables: summaryEnv },
    handler: "index.handler",
    memorySize: 512,
    name: "petstore-ts-summary",
    role: summaryRole.arn,
    runtime: "nodejs22.x",
    timeout: 30,
});

const webEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_KV_PETSBYOWNER_TABLE: pulumi.interpolate`${petsByOwnerTable.name}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_UNIT: `web`,
    CLOUDCC_UNIT_SUMMARY_FUNCTION: pulumi.interpolate`${summaryFn.name}`,
};

const webTask = new aws.ecs.TaskDefinition("web", {
    containerDefinitions: pulumi.jsonStringify([{
    environment: Object.entries(webEnv).map(([name, value]) => ({ name, value })),
    image: pulumi.interpolate`${webRepo.repositoryUrl}:latest`,
    logConfiguration: {
        logDriver: "awslogs",
        options: {
            "awslogs-group": webLogs.name,
            "awslogs-region": aws.config.region,
            "awslogs-stream-prefix": "web",
        },
    },
    name: "web",
    portMappings: [
        {
            containerPort: 8080,
            protocol: "tcp",
        },
    ],
}]),
    cpu: "256",
    executionRoleArn: webExecRole.arn,
    family: "petstore-ts-web",
    memory: "512",
    networkMode: "awsvpc",
    requiresCompatibilities: [
        "FARGATE",
    ],
    taskRoleArn: webTaskRole.arn,
});

const webPolicy = new aws.iam.RolePolicy("web", {
    name: "petstore-ts-web-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                petsByOwnerTable.arn,
                pulumi.interpolate`${petsByOwnerTable.arn}/index/*`,
            ],
        },
        {
            Action: [
                "lambda:InvokeFunction",
            ],
            Effect: "Allow",
            Resource: [
                summaryFn.arn,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: webTaskRole.id,
});

const networkVpc = new aws.ec2.Vpc("network", {
    cidrBlock: "10.0.0.0/16",
    enableDnsHostnames: true,
    enableDnsSupport: true,
    tags: {
        Name: "petstore-ts-network",
    },
});

const petApiTargetGroup = new aws.lb.TargetGroup("pet-api", {
    healthCheck: {
        matcher: "200-399",
        path: "/health",
    },
    name: "petstore-ts-pet-api-tg",
    port: 8080,
    protocol: "HTTP",
    targetType: "ip",
    vpcId: networkVpc.id,
});

const networkGateway = new aws.ec2.InternetGateway("network", {
    vpcId: networkVpc.id,
});

const networkRoutes = new aws.ec2.RouteTable("network", {
    routes: [
        {
            cidrBlock: "0.0.0.0/0",
            gatewayId: networkGateway.id,
        },
    ],
    vpcId: networkVpc.id,
});

const networkSecurityGroup = new aws.ec2.SecurityGroup("network", {
    description: "Managed by cloudcc: traffic between compiled units and their datastores",
    egress: [
        {
            cidrBlocks: [
                "0.0.0.0/0",
            ],
            fromPort: 0,
            protocol: "-1",
            toPort: 0,
        },
    ],
    ingress: [
        {
            cidrBlocks: [
                "0.0.0.0/0",
            ],
            description: "inbound from the load balancer and within the VPC",
            fromPort: 0,
            protocol: "-1",
            toPort: 0,
        },
    ],
    vpcId: networkVpc.id,
});

const network0Subnet = new aws.ec2.Subnet("network-0", {
    availabilityZone: networkZones.names.apply(n => n[0]),
    cidrBlock: "10.0.0.0/24",
    mapPublicIpOnLaunch: true,
    tags: {
        Name: "petstore-ts-network-0",
    },
    vpcId: networkVpc.id,
});

const network0RouteAssoc = new aws.ec2.RouteTableAssociation("network-0", {
    routeTableId: networkRoutes.id,
    subnetId: network0Subnet.id,
});

const network1Subnet = new aws.ec2.Subnet("network-1", {
    availabilityZone: networkZones.names.apply(n => n[1]),
    cidrBlock: "10.0.1.0/24",
    mapPublicIpOnLaunch: true,
    tags: {
        Name: "petstore-ts-network-1",
    },
    vpcId: networkVpc.id,
});

const petApiAlb = new aws.lb.LoadBalancer("pet-api", {
    internal: false,
    loadBalancerType: "application",
    name: "petstore-ts-pet-api",
    securityGroups: [
        networkSecurityGroup.id,
    ],
    subnets: [
        network0Subnet.id,
        network1Subnet.id,
    ],
});

const petApiListener = new aws.lb.Listener("pet-api", {
    defaultActions: [
        {
            targetGroupArn: petApiTargetGroup.arn,
            type: "forward",
        },
    ],
    loadBalancerArn: petApiAlb.arn,
    port: 80,
    protocol: "HTTP",
});

const webService = new aws.ecs.Service("web", {
    cluster: clusterCluster.id,
    desiredCount: 1,
    launchType: "FARGATE",
    loadBalancers: [
        {
            containerName: "web",
            containerPort: 8080,
            targetGroupArn: petApiTargetGroup.arn,
        },
    ],
    name: "petstore-ts-web",
    networkConfiguration: {
        assignPublicIp: true,
        securityGroups: [
            networkSecurityGroup.id,
        ],
        subnets: [
            network0Subnet.id,
            network1Subnet.id,
        ],
    },
    taskDefinition: webTask.arn,
});

const network1RouteAssoc = new aws.ec2.RouteTableAssociation("network-1", {
    routeTableId: networkRoutes.id,
    subnetId: network1Subnet.id,
});

// Stack outputs. Every environment binding is exported under the exact
// name the runtime shims read, so a compiled unit can be run locally with:
//   eval "$(pulumi output --json | jq -r 'to_entries[]|"export \(.key)=\(.value)"')"
export const CLOUDCC_ECR_WEB_URL = pulumi.interpolate`${webRepo.repositoryUrl}`;
export const CLOUDCC_GATEWAY_PET_API_URL = pulumi.interpolate`http://${petApiAlb.dnsName}`;
export const CLOUDCC_KV_PETSBYOWNER_TABLE = pulumi.interpolate`${petsByOwnerTable.name}`;
export const CLOUDCC_UNIT_SUMMARY_FUNCTION = pulumi.interpolate`${summaryFn.name}`;
export const petApiUrl = petApiAlb.dnsName;
