"""Architecture of nomnom, generated by cloudcc.

Diagram as code, using https://pypi.org/project/diagrams -- one icon per
capability, showing the service each one resolved to and how the program said
they are connected.

The supporting cast is deliberately absent: roles, policies, log groups and an
HTTP API's internal wiring all exist, and all of them are in architecture.mmd
and architecture.dot. This file answers "what is this system", not "what will
exist in the account".

    pip install diagrams   # and graphviz
    python architecture.py

Recompiling overwrites this file. Copy it before editing.
"""

from diagrams import Diagram, Edge
from diagrams.aws.compute import ElasticContainerServiceService, Lambda
from diagrams.aws.database import Dynamodb
from diagrams.aws.integration import SNS
from diagrams.aws.network import ElbApplicationLoadBalancer
from diagrams.aws.storage import S3
from diagrams.k8s.compute import Deploy
from diagrams.k8s.network import SVC

with Diagram(
    "nomnom",
    filename="nomnom-architecture",
    outformat="png",
    show=False,
    direction="LR",
):
    n_execution_unit_dispatch = Lambda("dispatch\nLambda")
    n_execution_unit_inventory = Lambda("inventory\nLambda")
    n_execution_unit_menu = Deploy("menu\nDeployment")
    n_execution_unit_notify = Lambda("notify\nLambda")
    n_execution_unit_pricing = Lambda("pricing\nLambda")
    n_execution_unit_storefront = ElasticContainerServiceService("storefront\nFargate")
    n_execution_unit_tracking = Lambda("tracking\nLambda")
    n_expose_nomnom_api = ElbApplicationLoadBalancer("nomnom-api\nLoad Balancer")
    n_expose_nomnom_menu = SVC("nomnom-menu\nService")
    n_persist_fs_notifications = S3("notifications\nS3")
    n_persist_kv_assignments = Dynamodb("assignments\nDynamoDB")
    n_persist_kv_menuPrices = Dynamodb("menuPrices\nDynamoDB")
    n_persist_kv_orders = Dynamodb("orders\nDynamoDB")
    n_persist_kv_reservations = Dynamodb("reservations\nDynamoDB")
    n_persist_kv_trackingEvents = Dynamodb("trackingEvents\nDynamoDB")
    n_pubsub_courierAssigned = SNS("courierAssigned\nSNS")
    n_pubsub_orderPlaced = SNS("orderPlaced\nSNS")

    n_execution_unit_dispatch >> Edge(label="calls", color="darkorange", style="bold") >> n_execution_unit_inventory
    n_execution_unit_storefront >> Edge(label="calls", color="darkorange", style="bold") >> n_execution_unit_inventory
    n_execution_unit_storefront >> Edge(label="calls", color="darkorange", style="bold") >> n_execution_unit_pricing
    n_execution_unit_storefront >> Edge(label="calls", color="darkorange", style="bold") >> n_execution_unit_tracking
    n_expose_nomnom_api >> n_execution_unit_storefront
    n_expose_nomnom_menu >> n_execution_unit_menu
    n_execution_unit_dispatch >> Edge(label="publishes") >> n_pubsub_courierAssigned
    n_execution_unit_storefront >> Edge(label="publishes") >> n_pubsub_orderPlaced
    n_pubsub_orderPlaced >> Edge(label="subscribes", style="dashed") >> n_execution_unit_dispatch
    n_pubsub_courierAssigned >> Edge(label="subscribes", style="dashed") >> n_execution_unit_notify
    n_pubsub_orderPlaced >> Edge(label="subscribes", style="dashed") >> n_execution_unit_notify
    n_pubsub_courierAssigned >> Edge(label="subscribes", style="dashed") >> n_execution_unit_tracking
    n_execution_unit_dispatch >> n_persist_kv_assignments
    n_execution_unit_inventory >> n_persist_kv_reservations
    n_execution_unit_notify >> n_persist_fs_notifications
    n_execution_unit_pricing >> n_persist_kv_menuPrices
    n_execution_unit_storefront >> n_persist_kv_orders
    n_execution_unit_tracking >> n_persist_kv_trackingEvents
