"""Generated by cloudcc. Lambda entrypoint for execution unit "main".

Do not edit: recompiling overwrites this file.
"""

import importlib

from _cloudcc_runtime import pubsub as _cloudcc_pubsub

_module = importlib.import_module("app")

from mangum import Mangum

_asgi = Mangum(getattr(_module, "app"), lifespan="off")


def handler(event, context):
    """Route the invocation to the right adapter.

    A single unit can be both an HTTP handler and a topic subscriber, so the
    event shape decides: SNS deliveries go to the registered subscribers, and
    anything else is treated as an HTTP request.
    """
    if _cloudcc_pubsub.is_sns_event(event):
        return _cloudcc_pubsub.dispatch(event)
    return _asgi(event, context)
