// Generated by cloudcc for application "nomnom-ts". Do not edit: recompiling overwrites
// this file. To change what is generated, edit cloudcc.yaml in your source tree.
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as k8s from "@pulumi/kubernetes";

const networkZones = aws.getAvailabilityZonesOutput({
    state: "available",
});

const dispatchLogs = new aws.cloudwatch.LogGroup("dispatch", {
    name: "/aws/lambda/nomnom-ts-dispatch",
    retentionInDays: 14,
});

const inventoryLogs = new aws.cloudwatch.LogGroup("inventory", {
    name: "/aws/lambda/nomnom-ts-inventory",
    retentionInDays: 14,
});

const notifyLogs = new aws.cloudwatch.LogGroup("notify", {
    name: "/aws/lambda/nomnom-ts-notify",
    retentionInDays: 14,
});

const pricingLogs = new aws.cloudwatch.LogGroup("pricing", {
    name: "/aws/lambda/nomnom-ts-pricing",
    retentionInDays: 14,
});

const storefrontLogs = new aws.cloudwatch.LogGroup("storefront", {
    name: "/ecs/nomnom-ts-storefront",
    retentionInDays: 14,
});

const trackingLogs = new aws.cloudwatch.LogGroup("tracking", {
    name: "/aws/lambda/nomnom-ts-tracking",
    retentionInDays: 14,
});

const assignmentsTable = new aws.dynamodb.Table("assignments", {
    attributes: [
        {
            name: "id",
            type: "S",
        },
    ],
    billingMode: "PAY_PER_REQUEST",
    hashKey: "id",
    name: "nomnom-ts-assignments",
});

const menuPricesTable = new aws.dynamodb.Table("menuPrices", {
    attributes: [
        {
            name: "id",
            type: "S",
        },
    ],
    billingMode: "PAY_PER_REQUEST",
    hashKey: "id",
    name: "nomnom-ts-menuPrices",
});

const ordersTable = new aws.dynamodb.Table("orders", {
    attributes: [
        {
            name: "id",
            type: "S",
        },
    ],
    billingMode: "PAY_PER_REQUEST",
    hashKey: "id",
    name: "nomnom-ts-orders",
});

const reservationsTable = new aws.dynamodb.Table("reservations", {
    attributes: [
        {
            name: "id",
            type: "S",
        },
    ],
    billingMode: "PAY_PER_REQUEST",
    hashKey: "id",
    name: "nomnom-ts-reservations",
});

const trackingEventsTable = new aws.dynamodb.Table("trackingEvents", {
    attributes: [
        {
            name: "id",
            type: "S",
        },
    ],
    billingMode: "PAY_PER_REQUEST",
    hashKey: "id",
    name: "nomnom-ts-trackingEvents",
});

const menuRepo = new aws.ecr.Repository("menu", {
    forceDelete: true,
    name: "nomnom-ts-menu",
});

const storefrontRepo = new aws.ecr.Repository("storefront", {
    forceDelete: true,
    name: "nomnom-ts-storefront",
});

const clusterCluster = new aws.ecs.Cluster("cluster", {
    name: "nomnom-ts-cluster",
});

const storefrontExecRole = new aws.iam.Role("storefront-exec", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "ecs-tasks.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy",
    ],
    name: "nomnom-ts-storefront-exec",
});

const storefrontTaskRole = new aws.iam.Role("storefront-task", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "ecs-tasks.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    name: "nomnom-ts-storefront-task",
});

const kubernetesRole = new aws.iam.Role("kubernetes", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "eks.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy",
    ],
    name: "nomnom-ts-kubernetes-cluster",
});

const kubernetesRole2 = new aws.iam.Role("kubernetes-2", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "ec2.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
        "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
        "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly",
    ],
    name: "nomnom-ts-kubernetes-node",
});

const dispatchRole = new aws.iam.Role("dispatch", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "nomnom-ts-dispatch-role",
});

const inventoryRole = new aws.iam.Role("inventory", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "nomnom-ts-inventory-role",
});

const inventoryPolicy = new aws.iam.RolePolicy("inventory", {
    name: "nomnom-ts-inventory-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                reservationsTable.arn,
                pulumi.interpolate`${reservationsTable.arn}/index/*`,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: inventoryRole.id,
});

const notifyRole = new aws.iam.Role("notify", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "nomnom-ts-notify-role",
});

const pricingRole = new aws.iam.Role("pricing", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "nomnom-ts-pricing-role",
});

const pricingPolicy = new aws.iam.RolePolicy("pricing", {
    name: "nomnom-ts-pricing-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                menuPricesTable.arn,
                pulumi.interpolate`${menuPricesTable.arn}/index/*`,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: pricingRole.id,
});

const trackingRole = new aws.iam.Role("tracking", {
    assumeRolePolicy: pulumi.jsonStringify({
    Statement: [
        {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
                Service: "lambda.amazonaws.com",
            },
        },
    ],
    Version: "2012-10-17",
}),
    managedPolicyArns: [
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ],
    name: "nomnom-ts-tracking-role",
});

const trackingPolicy = new aws.iam.RolePolicy("tracking", {
    name: "nomnom-ts-tracking-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                trackingEventsTable.arn,
                pulumi.interpolate`${trackingEventsTable.arn}/index/*`,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: trackingRole.id,
});

const inventoryEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_KV_RESERVATIONS_TABLE: pulumi.interpolate`${reservationsTable.name}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_UNIT: `inventory`,
};

const inventoryFn = new aws.lambda.Function("inventory", {
    code: new pulumi.asset.FileArchive("build/inventory.zip"),
    environment: { variables: inventoryEnv },
    handler: "index.handler",
    memorySize: 512,
    name: "nomnom-ts-inventory",
    role: inventoryRole.arn,
    runtime: "nodejs22.x",
    timeout: 30,
});

const pricingEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_KV_MENUPRICES_TABLE: pulumi.interpolate`${menuPricesTable.name}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_UNIT: `pricing`,
};

const pricingFn = new aws.lambda.Function("pricing", {
    code: new pulumi.asset.FileArchive("build/pricing.zip"),
    environment: { variables: pricingEnv },
    handler: "index.handler",
    memorySize: 512,
    name: "nomnom-ts-pricing",
    role: pricingRole.arn,
    runtime: "nodejs22.x",
    timeout: 30,
});

const notificationsBucket = new aws.s3.BucketV2("notifications", {
    bucket: "nomnom-ts-notifications",
    forceDestroy: true,
});

const notifyPolicy = new aws.iam.RolePolicy("notify", {
    name: "nomnom-ts-notify-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
            ],
            Effect: "Allow",
            Resource: [
                notificationsBucket.arn,
                pulumi.interpolate`${notificationsBucket.arn}/*`,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: notifyRole.id,
});

const courierAssignedTopic = new aws.sns.Topic("courierAssigned", {
    name: "nomnom-ts-courierAssigned",
});

const dispatchPolicy = new aws.iam.RolePolicy("dispatch", {
    name: "nomnom-ts-dispatch-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                assignmentsTable.arn,
                pulumi.interpolate`${assignmentsTable.arn}/index/*`,
            ],
        },
        {
            Action: [
                "lambda:InvokeFunction",
            ],
            Effect: "Allow",
            Resource: [
                inventoryFn.arn,
            ],
        },
        {
            Action: [
                "sns:Publish",
            ],
            Effect: "Allow",
            Resource: [
                courierAssignedTopic.arn,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: dispatchRole.id,
});

const orderPlacedTopic = new aws.sns.Topic("orderPlaced", {
    name: "nomnom-ts-orderPlaced",
});

const dispatchEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_KV_ASSIGNMENTS_TABLE: pulumi.interpolate`${assignmentsTable.name}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_TOPIC_COURIERASSIGNED_ARN: pulumi.interpolate`${courierAssignedTopic.arn}`,
    CLOUDCC_TOPIC_COURIERASSIGNED_BACKING: "sns",
    CLOUDCC_TOPIC_ORDERPLACED_ARN: pulumi.interpolate`${orderPlacedTopic.arn}`,
    CLOUDCC_TOPIC_ORDERPLACED_BACKING: "sns",
    CLOUDCC_UNIT: `dispatch`,
    CLOUDCC_UNIT_INVENTORY_FUNCTION: pulumi.interpolate`${inventoryFn.name}`,
};

const dispatchFn = new aws.lambda.Function("dispatch", {
    code: new pulumi.asset.FileArchive("build/dispatch.zip"),
    environment: { variables: dispatchEnv },
    handler: "index.handler",
    memorySize: 512,
    name: "nomnom-ts-dispatch",
    role: dispatchRole.arn,
    runtime: "nodejs22.x",
    timeout: 30,
});

const dispatchOrderPlacedSnsPermission = new aws.lambda.Permission("dispatch-orderPlaced-sns", {
    action: "lambda:InvokeFunction",
    function: dispatchFn.name,
    principal: "sns.amazonaws.com",
    sourceArn: orderPlacedTopic.arn,
    statementId: "nomnom-ts-dispatch-orderPlaced-sns",
});

const notifyEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_FS_NOTIFICATIONS_BUCKET: pulumi.interpolate`${notificationsBucket.bucket}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_TOPIC_COURIERASSIGNED_ARN: pulumi.interpolate`${courierAssignedTopic.arn}`,
    CLOUDCC_TOPIC_COURIERASSIGNED_BACKING: "sns",
    CLOUDCC_TOPIC_ORDERPLACED_ARN: pulumi.interpolate`${orderPlacedTopic.arn}`,
    CLOUDCC_TOPIC_ORDERPLACED_BACKING: "sns",
    CLOUDCC_UNIT: `notify`,
};

const notifyFn = new aws.lambda.Function("notify", {
    code: new pulumi.asset.FileArchive("build/notify.zip"),
    environment: { variables: notifyEnv },
    handler: "index.handler",
    memorySize: 512,
    name: "nomnom-ts-notify",
    role: notifyRole.arn,
    runtime: "nodejs22.x",
    timeout: 30,
});

const notifyCourierAssignedSnsPermission = new aws.lambda.Permission("notify-courierAssigned-sns", {
    action: "lambda:InvokeFunction",
    function: notifyFn.name,
    principal: "sns.amazonaws.com",
    sourceArn: courierAssignedTopic.arn,
    statementId: "nomnom-ts-notify-courierAssigned-sns",
});

const notifyOrderPlacedSnsPermission = new aws.lambda.Permission("notify-orderPlaced-sns", {
    action: "lambda:InvokeFunction",
    function: notifyFn.name,
    principal: "sns.amazonaws.com",
    sourceArn: orderPlacedTopic.arn,
    statementId: "nomnom-ts-notify-orderPlaced-sns",
});

const trackingEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_KV_TRACKINGEVENTS_TABLE: pulumi.interpolate`${trackingEventsTable.name}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_TOPIC_COURIERASSIGNED_ARN: pulumi.interpolate`${courierAssignedTopic.arn}`,
    CLOUDCC_TOPIC_COURIERASSIGNED_BACKING: "sns",
    CLOUDCC_TOPIC_ORDERPLACED_ARN: pulumi.interpolate`${orderPlacedTopic.arn}`,
    CLOUDCC_TOPIC_ORDERPLACED_BACKING: "sns",
    CLOUDCC_UNIT: `tracking`,
};

const trackingFn = new aws.lambda.Function("tracking", {
    code: new pulumi.asset.FileArchive("build/tracking.zip"),
    environment: { variables: trackingEnv },
    handler: "index.handler",
    memorySize: 512,
    name: "nomnom-ts-tracking",
    role: trackingRole.arn,
    runtime: "nodejs22.x",
    timeout: 30,
});

const storefrontEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_KV_ORDERS_TABLE: pulumi.interpolate`${ordersTable.name}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_TOPIC_COURIERASSIGNED_ARN: pulumi.interpolate`${courierAssignedTopic.arn}`,
    CLOUDCC_TOPIC_COURIERASSIGNED_BACKING: "sns",
    CLOUDCC_TOPIC_ORDERPLACED_ARN: pulumi.interpolate`${orderPlacedTopic.arn}`,
    CLOUDCC_TOPIC_ORDERPLACED_BACKING: "sns",
    CLOUDCC_UNIT: `storefront`,
    CLOUDCC_UNIT_INVENTORY_FUNCTION: pulumi.interpolate`${inventoryFn.name}`,
    CLOUDCC_UNIT_PRICING_FUNCTION: pulumi.interpolate`${pricingFn.name}`,
    CLOUDCC_UNIT_TRACKING_FUNCTION: pulumi.interpolate`${trackingFn.name}`,
};

const storefrontTask = new aws.ecs.TaskDefinition("storefront", {
    containerDefinitions: pulumi.jsonStringify([{
    environment: Object.entries(storefrontEnv).map(([name, value]) => ({ name, value })),
    image: pulumi.interpolate`${storefrontRepo.repositoryUrl}:latest`,
    logConfiguration: {
        logDriver: "awslogs",
        options: {
            "awslogs-group": storefrontLogs.name,
            "awslogs-region": aws.config.region,
            "awslogs-stream-prefix": "storefront",
        },
    },
    name: "storefront",
    portMappings: [
        {
            containerPort: 8080,
            protocol: "tcp",
        },
    ],
}]),
    cpu: "256",
    executionRoleArn: storefrontExecRole.arn,
    family: "nomnom-ts-storefront",
    memory: "1024",
    networkMode: "awsvpc",
    requiresCompatibilities: [
        "FARGATE",
    ],
    taskRoleArn: storefrontTaskRole.arn,
});

const storefrontPolicy = new aws.iam.RolePolicy("storefront", {
    name: "nomnom-ts-storefront-policy",
    policy: pulumi.jsonStringify({
    Statement: [
        {
            Action: [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
            ],
            Effect: "Allow",
            Resource: [
                ordersTable.arn,
                pulumi.interpolate`${ordersTable.arn}/index/*`,
            ],
        },
        {
            Action: [
                "lambda:InvokeFunction",
            ],
            Effect: "Allow",
            Resource: [
                inventoryFn.arn,
            ],
        },
        {
            Action: [
                "lambda:InvokeFunction",
            ],
            Effect: "Allow",
            Resource: [
                pricingFn.arn,
            ],
        },
        {
            Action: [
                "lambda:InvokeFunction",
            ],
            Effect: "Allow",
            Resource: [
                trackingFn.arn,
            ],
        },
        {
            Action: [
                "sns:Publish",
            ],
            Effect: "Allow",
            Resource: [
                orderPlacedTopic.arn,
            ],
        },
    ],
    Version: "2012-10-17",
}),
    role: storefrontTaskRole.id,
});

const trackingCourierAssignedSnsPermission = new aws.lambda.Permission("tracking-courierAssigned-sns", {
    action: "lambda:InvokeFunction",
    function: trackingFn.name,
    principal: "sns.amazonaws.com",
    sourceArn: courierAssignedTopic.arn,
    statementId: "nomnom-ts-tracking-courierAssigned-sns",
});

const dispatchOrderPlacedSubscription = new aws.sns.TopicSubscription("dispatch-orderPlaced", {
    endpoint: dispatchFn.arn,
    protocol: "lambda",
    topic: orderPlacedTopic.arn,
});

const notifyCourierAssignedSubscription = new aws.sns.TopicSubscription("notify-courierAssigned", {
    endpoint: notifyFn.arn,
    protocol: "lambda",
    topic: courierAssignedTopic.arn,
});

const notifyOrderPlacedSubscription = new aws.sns.TopicSubscription("notify-orderPlaced", {
    endpoint: notifyFn.arn,
    protocol: "lambda",
    topic: orderPlacedTopic.arn,
});

const trackingCourierAssignedSubscription = new aws.sns.TopicSubscription("tracking-courierAssigned", {
    endpoint: trackingFn.arn,
    protocol: "lambda",
    topic: courierAssignedTopic.arn,
});

const networkVpc = new aws.ec2.Vpc("network", {
    cidrBlock: "10.0.0.0/16",
    enableDnsHostnames: true,
    enableDnsSupport: true,
    tags: {
        Name: "nomnom-ts-network",
    },
});

const nomnomApiTargetGroup = new aws.lb.TargetGroup("nomnom-api", {
    healthCheck: {
        matcher: "200-399",
        path: "/health",
    },
    name: "nomnom-ts-nomnom-api-tg",
    port: 8080,
    protocol: "HTTP",
    targetType: "ip",
    vpcId: networkVpc.id,
});

const networkGateway = new aws.ec2.InternetGateway("network", {
    vpcId: networkVpc.id,
});

const networkRoutes = new aws.ec2.RouteTable("network", {
    routes: [
        {
            cidrBlock: "0.0.0.0/0",
            gatewayId: networkGateway.id,
        },
    ],
    vpcId: networkVpc.id,
});

const networkSecurityGroup = new aws.ec2.SecurityGroup("network", {
    description: "Managed by cloudcc: traffic between compiled units and their datastores",
    egress: [
        {
            cidrBlocks: [
                "0.0.0.0/0",
            ],
            fromPort: 0,
            protocol: "-1",
            toPort: 0,
        },
    ],
    ingress: [
        {
            cidrBlocks: [
                "0.0.0.0/0",
            ],
            description: "inbound from the load balancer and within the VPC",
            fromPort: 0,
            protocol: "-1",
            toPort: 0,
        },
    ],
    vpcId: networkVpc.id,
});

const network0Subnet = new aws.ec2.Subnet("network-0", {
    availabilityZone: networkZones.names.apply(n => n[0]),
    cidrBlock: "10.0.0.0/24",
    mapPublicIpOnLaunch: true,
    tags: {
        Name: "nomnom-ts-network-0",
    },
    vpcId: networkVpc.id,
});

const network0RouteAssoc = new aws.ec2.RouteTableAssociation("network-0", {
    routeTableId: networkRoutes.id,
    subnetId: network0Subnet.id,
});

const network1Subnet = new aws.ec2.Subnet("network-1", {
    availabilityZone: networkZones.names.apply(n => n[1]),
    cidrBlock: "10.0.1.0/24",
    mapPublicIpOnLaunch: true,
    tags: {
        Name: "nomnom-ts-network-1",
    },
    vpcId: networkVpc.id,
});

const nomnomApiAlb = new aws.lb.LoadBalancer("nomnom-api", {
    internal: false,
    loadBalancerType: "application",
    name: "nomnom-ts-nomnom-api",
    securityGroups: [
        networkSecurityGroup.id,
    ],
    subnets: [
        network0Subnet.id,
        network1Subnet.id,
    ],
});

const nomnomApiListener = new aws.lb.Listener("nomnom-api", {
    defaultActions: [
        {
            targetGroupArn: nomnomApiTargetGroup.arn,
            type: "forward",
        },
    ],
    loadBalancerArn: nomnomApiAlb.arn,
    port: 80,
    protocol: "HTTP",
});

const storefrontService = new aws.ecs.Service("storefront", {
    cluster: clusterCluster.id,
    desiredCount: 1,
    launchType: "FARGATE",
    loadBalancers: [
        {
            containerName: "storefront",
            containerPort: 8080,
            targetGroupArn: nomnomApiTargetGroup.arn,
        },
    ],
    name: "nomnom-ts-storefront",
    networkConfiguration: {
        assignPublicIp: true,
        securityGroups: [
            networkSecurityGroup.id,
        ],
        subnets: [
            network0Subnet.id,
            network1Subnet.id,
        ],
    },
    taskDefinition: storefrontTask.arn,
});

const kubernetesEks = new aws.eks.Cluster("kubernetes", {
    name: "nomnom-ts-kubernetes",
    roleArn: kubernetesRole.arn,
    vpcConfig: {
        subnetIds: [
            network0Subnet.id,
            network1Subnet.id,
        ],
    },
});

const kubernetesNodes = new aws.eks.NodeGroup("kubernetes", {
    clusterName: kubernetesEks.name,
    nodeGroupName: "nomnom-ts-kubernetes-nodes",
    nodeRoleArn: kubernetesRole2.arn,
    scalingConfig: {
        desiredSize: 1,
        maxSize: 2,
        minSize: 1,
    },
    subnetIds: [
        network0Subnet.id,
        network1Subnet.id,
    ],
});

const network1RouteAssoc = new aws.ec2.RouteTableAssociation("network-1", {
    routeTableId: networkRoutes.id,
    subnetId: network1Subnet.id,
});

const kubernetesK8s = new k8s.Provider("kubernetes", {
    kubeconfig: process.env.CLOUDCC_KUBECONFIG ?? pulumi.interpolate`apiVersion: v1
clusters:
- cluster:
    server: ${kubernetesEks.endpoint}
    certificate-authority-data: ${kubernetesEks.certificateAuthority.data}
  name: cloudcc
contexts:
- context:
    cluster: cloudcc
    user: cloudcc
  name: cloudcc
current-context: cloudcc
kind: Config
users:
- name: cloudcc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args: ["eks", "get-token", "--cluster-name", "${kubernetesEks.name}"]
`,
});

const menuEnv: { [key: string]: pulumi.Input<string> } = {
    CLOUDCC_AWS_ENDPOINT_URL: pulumi.interpolate`${process.env.CLOUDCC_AWS_ENDPOINT_URL ?? ""}`,
    CLOUDCC_LOG_DESTINATION: `cloudwatch`,
    CLOUDCC_UNIT: `menu`,
};

const menuDeployment = new k8s.apps.v1.Deployment("menu", {
    metadata: {
        labels: {
            app: "menu",
        },
        name: "nomnom-ts-menu",
    },
    spec: {
        replicas: 1,
        selector: {
            matchLabels: {
                app: "menu",
            },
        },
        template: {
            metadata: {
                labels: {
                    app: "menu",
                },
            },
            spec: {
                containers: [
                    {
                        env: Object.entries(menuEnv).map(([name, value]) => ({ name, value: value as pulumi.Input<string> })),
                        image: pulumi.interpolate`${menuRepo.repositoryUrl}:latest`,
                        name: "menu",
                        ports: [
                            {
                                containerPort: 8080,
                            },
                        ],
                        resources: {
                            limits: {
                                cpu: "250m",
                                memory: "512Mi",
                            },
                            requests: {
                                cpu: "250m",
                                memory: "512Mi",
                            },
                        },
                    },
                ],
            },
        },
    },
}, {
    provider: kubernetesK8s,
});

const menuSvc = new k8s.core.v1.Service("menu", {
    metadata: {
        labels: {
            app: "menu",
        },
        name: "nomnom-ts-menu",
    },
    spec: {
        ports: [
            {
                port: 80,
                protocol: "TCP",
                targetPort: 8080,
            },
        ],
        selector: {
            app: "menu",
        },
        type: "LoadBalancer",
    },
}, {
    dependsOn: [
        menuDeployment,
    ],
    provider: kubernetesK8s,
});

// Stack outputs. Every environment binding is exported under the exact
// name the runtime shims read, so a compiled unit can be run locally with:
//   eval "$(pulumi output --json | jq -r 'to_entries[]|"export \(.key)=\(.value)"')"
export const CLOUDCC_CLUSTER_KUBERNETES_ENDPOINT = pulumi.interpolate`${kubernetesEks.endpoint}`;
export const CLOUDCC_ECR_MENU_URL = pulumi.interpolate`${menuRepo.repositoryUrl}`;
export const CLOUDCC_ECR_STOREFRONT_URL = pulumi.interpolate`${storefrontRepo.repositoryUrl}`;
export const CLOUDCC_FS_NOTIFICATIONS_BUCKET = pulumi.interpolate`${notificationsBucket.bucket}`;
export const CLOUDCC_GATEWAY_NOMNOM_API_URL = pulumi.interpolate`http://${nomnomApiAlb.dnsName}`;
export const CLOUDCC_KV_ASSIGNMENTS_TABLE = pulumi.interpolate`${assignmentsTable.name}`;
export const CLOUDCC_KV_MENUPRICES_TABLE = pulumi.interpolate`${menuPricesTable.name}`;
export const CLOUDCC_KV_ORDERS_TABLE = pulumi.interpolate`${ordersTable.name}`;
export const CLOUDCC_KV_RESERVATIONS_TABLE = pulumi.interpolate`${reservationsTable.name}`;
export const CLOUDCC_KV_TRACKINGEVENTS_TABLE = pulumi.interpolate`${trackingEventsTable.name}`;
export const CLOUDCC_TOPIC_COURIERASSIGNED_ARN = pulumi.interpolate`${courierAssignedTopic.arn}`;
export const CLOUDCC_TOPIC_COURIERASSIGNED_BACKING = "sns";
export const CLOUDCC_TOPIC_ORDERPLACED_ARN = pulumi.interpolate`${orderPlacedTopic.arn}`;
export const CLOUDCC_TOPIC_ORDERPLACED_BACKING = "sns";
export const CLOUDCC_UNIT_DISPATCH_FUNCTION = pulumi.interpolate`${dispatchFn.name}`;
export const CLOUDCC_UNIT_INVENTORY_FUNCTION = pulumi.interpolate`${inventoryFn.name}`;
export const CLOUDCC_UNIT_NOTIFY_FUNCTION = pulumi.interpolate`${notifyFn.name}`;
export const CLOUDCC_UNIT_PRICING_FUNCTION = pulumi.interpolate`${pricingFn.name}`;
export const CLOUDCC_UNIT_TRACKING_FUNCTION = pulumi.interpolate`${trackingFn.name}`;
export const kubernetesUrl = kubernetesEks.endpoint;
export const nomnomApiUrl = nomnomApiAlb.dnsName;
