"""Generated by cloudcc. Lambda entrypoint for execution unit "dispatch".

Do not edit: recompiling overwrites this file.
"""

import importlib

from _cloudcc_runtime import pubsub as _cloudcc_pubsub
from _cloudcc_runtime import rpc as _cloudcc_rpc

_module = importlib.import_module("nomnom.dispatch")


def handler(event, context):
    """Route the invocation to the right adapter.

    A single unit can be an HTTP handler, a topic subscriber and callable by
    other units all at once, so the event shape decides: a call envelope goes
    to the named function, a topic or queue delivery goes to the registered
    subscribers, and anything else is treated as an HTTP request.
    """
    if _cloudcc_rpc.is_call(event):
        return _cloudcc_rpc.dispatch(_module, event)
    if _cloudcc_pubsub.is_delivery(event):
        return _cloudcc_pubsub.dispatch(event)
    return {"unit": "dispatch", "handled": False}
